apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: bundles.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: Bundle
    plural: bundles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        components:
          items:
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              metadata:
                type: object
              spec:
                properties:
                  appVersion:
                    type: string
                  componentName:
                    type: string
                  objects:
                    items:
                      type: object
                    type: array
                  version:
                    type: string
                type: object
            type: object
          type: array
        kind:
          type: string
        metadata:
          type: object
        setName:
          type: string
        version:
          type: string
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
