apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: componentsets.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: ComponentSet
    plural: componentsets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            components:
              items:
                properties:
                  componentName:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            setName:
              type: string
            version:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
