apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: componentsetlists.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: ComponentSetList
    plural: componentsetlists
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        items:
          items:
            properties:
              apiVersion:
                description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                type: string
              kind:
                description: 'Kind is a string value representing the REST resource
                  this object represents. Servers may infer this from the endpoint
                  the client submits requests to. Cannot be updated. In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                type: string
              metadata:
                type: object
              spec:
                description: The specification object for the ComponentSet
                properties:
                  components:
                    description: Components are references to component objects that
                      make up the component set. To get the Metadata.Name for the
                      component, GetLocalObjectRef() should be called on the component
                      reference.
                    items:
                      properties:
                        componentName:
                          description: ComponentName is the readable name of a component.
                          type: string
                        version:
                          description: Version is the version string for a component.
                          type: string
                      type: object
                    type: array
                  setName:
                    description: SetName is the human-readable string for this group
                      of components. It must only contain lower case alphanumerics,
                      periods, and dashes. See more details at k8s.io/docs/concepts/overview/working-with-objects/names/
                    type: string
                  version:
                    description: Version is the required version string for this component
                      set and should have the form X.Y.Z (Major.Minor.Patch). Generally
                      speaking, major-version changes should indicate breaking changes,
                      minor-versions should indicate backwards compatible features,
                      and patch changes should indicate backwords compatible. If there
                      are any changes to the bundle, then the version string must
                      be incremented. As such, the version should not be tied to the
                      version of the container images.
                    type: string
                type: object
            type: object
          type: array
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
