apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: bundlebuilders.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: BundleBuilder
    plural: bundlebuilders
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        componentFiles:
          items:
            properties:
              digest:
                type: string
              url:
                type: string
            type: object
          type: array
        kind:
          type: string
        metadata:
          type: object
        setName:
          type: string
        version:
          type: string
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
