apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: componentpackagebuilders.bundleext.gke.io
spec:
  group: bundleext.gke.io
  names:
    kind: ComponentPackageBuilder
    plural: componentpackagebuilders
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        componentName:
          type: string
        kind:
          type: string
        metadata:
          type: object
        objectFiles:
          items:
            properties:
              digest:
                type: string
              url:
                type: string
            type: object
          type: array
        rawTextFiles:
          items:
            properties:
              files:
                items:
                  properties:
                    digest:
                      type: string
                    url:
                      type: string
                  type: object
                type: array
              name:
                type: string
            type: object
          type: array
        version:
          type: string
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
