// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundleext/v1alpha1/node_config.proto

package v1alpha1

import (
	fmt "fmt"
	v1alpha1 "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Configuration for node images. This is a resource that provides information
// about which images are available for node creation and how to initialize the
// node images.
type NodeConfig struct {
	// Required. Kubernetes API Version for the NodeConfig type.
	// Should be 'bundleext.gke.io/v1alpha1'
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Required. The Kubernetes `kind` for this object. Must always be
	// 'NodeConfig'.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kubernetes Metadata for the node config. The Metadata.name field must be
	// filled out and each node config in a bundle must have a unique name. For
	// example you might have a 'master-node-config' component or perhaps even a
	// 'gpu-config' config.
	Metadata *v1alpha1.ObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Initialization file to run on VM startup. The contents of this init file
	// will depend a great deal on the specific environment and operation system.
	//
	// Types that are valid to be assigned to InitData:
	//	*NodeConfig_InitFile
	//	*NodeConfig_ExternalInitFile
	InitData isNodeConfig_InitData `protobuf_oneof:"init_data"`
	// Envirnoment variables to set before startup to configure the init script.
	EnvVars []*EnvVar `protobuf:"bytes,6,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	// The OS image to use for VM creation.
	OsImage              *v1alpha1.File `protobuf:"bytes,7,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4df58a757fafe70a, []int{0}
}

func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (m *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(m, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *NodeConfig) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *NodeConfig) GetMetadata() *v1alpha1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isNodeConfig_InitData interface {
	isNodeConfig_InitData()
}

type NodeConfig_InitFile struct {
	InitFile string `protobuf:"bytes,4,opt,name=init_file,json=initFile,proto3,oneof"`
}

type NodeConfig_ExternalInitFile struct {
	ExternalInitFile *v1alpha1.File `protobuf:"bytes,5,opt,name=external_init_file,json=externalInitFile,proto3,oneof"`
}

func (*NodeConfig_InitFile) isNodeConfig_InitData() {}

func (*NodeConfig_ExternalInitFile) isNodeConfig_InitData() {}

func (m *NodeConfig) GetInitData() isNodeConfig_InitData {
	if m != nil {
		return m.InitData
	}
	return nil
}

func (m *NodeConfig) GetInitFile() string {
	if x, ok := m.GetInitData().(*NodeConfig_InitFile); ok {
		return x.InitFile
	}
	return ""
}

func (m *NodeConfig) GetExternalInitFile() *v1alpha1.File {
	if x, ok := m.GetInitData().(*NodeConfig_ExternalInitFile); ok {
		return x.ExternalInitFile
	}
	return nil
}

func (m *NodeConfig) GetEnvVars() []*EnvVar {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *NodeConfig) GetOsImage() *v1alpha1.File {
	if m != nil {
		return m.OsImage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NodeConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NodeConfig_OneofMarshaler, _NodeConfig_OneofUnmarshaler, _NodeConfig_OneofSizer, []interface{}{
		(*NodeConfig_InitFile)(nil),
		(*NodeConfig_ExternalInitFile)(nil),
	}
}

func _NodeConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExternalInitFile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NodeConfig.InitData has unexpected type %T", x)
	}
	return nil
}

func _NodeConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NodeConfig)
	switch tag {
	case 4: // init_data.init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.InitData = &NodeConfig_InitFile{x}
		return true, err
	case 5: // init_data.external_init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(v1alpha1.File)
		err := b.DecodeMessage(msg)
		m.InitData = &NodeConfig_ExternalInitFile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NodeConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.InitFile)))
		n += len(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		s := proto.Size(x.ExternalInitFile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// An environment variable specified for node startup.
type EnvVar struct {
	// Name of this environment variable. E.g., FOO_VAR. The name of the
	// environment variable should be unique within a node bootstrap
	// configuration.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value to set for this environment variable.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvVar) Reset()         { *m = EnvVar{} }
func (m *EnvVar) String() string { return proto.CompactTextString(m) }
func (*EnvVar) ProtoMessage()    {}
func (*EnvVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_4df58a757fafe70a, []int{1}
}

func (m *EnvVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvVar.Unmarshal(m, b)
}
func (m *EnvVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvVar.Marshal(b, m, deterministic)
}
func (m *EnvVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvVar.Merge(m, src)
}
func (m *EnvVar) XXX_Size() int {
	return xxx_messageInfo_EnvVar.Size(m)
}
func (m *EnvVar) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvVar.DiscardUnknown(m)
}

var xxx_messageInfo_EnvVar proto.InternalMessageInfo

func (m *EnvVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeConfig)(nil), "pkg.apis.bundleext.v1alpha1.NodeConfig")
	proto.RegisterType((*EnvVar)(nil), "pkg.apis.bundleext.v1alpha1.EnvVar")
}

func init() {
	proto.RegisterFile("pkg/apis/bundleext/v1alpha1/node_config.proto", fileDescriptor_4df58a757fafe70a)
}

var fileDescriptor_4df58a757fafe70a = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0x6f, 0xdb, 0x30,
	0x10, 0x8d, 0xf3, 0x61, 0x2b, 0xf4, 0x52, 0x10, 0x1d, 0x84, 0x14, 0x0d, 0x8c, 0xb4, 0x83, 0x51,
	0xd4, 0x14, 0xe2, 0x2e, 0xed, 0x52, 0x14, 0x09, 0xda, 0x26, 0x83, 0xed, 0x42, 0x83, 0x87, 0x2e,
	0x02, 0x25, 0x9d, 0x65, 0x56, 0x14, 0x4f, 0x10, 0x29, 0xc1, 0x7f, 0xbd, 0x5b, 0x41, 0x4a, 0xb6,
	0x0b, 0x03, 0x36, 0x32, 0xe9, 0xee, 0xf4, 0xee, 0xdd, 0xbd, 0xc7, 0x23, 0x93, 0x32, 0xcf, 0x02,
	0x5e, 0x0a, 0x1d, 0xc4, 0xb5, 0x4a, 0x25, 0xc0, 0xc6, 0x04, 0xcd, 0x3d, 0x97, 0xe5, 0x9a, 0xdf,
	0x07, 0x0a, 0x53, 0x88, 0x12, 0x54, 0x2b, 0x91, 0xb1, 0xb2, 0x42, 0x83, 0xf4, 0x4d, 0x99, 0x67,
	0xcc, 0xc2, 0xd9, 0x0e, 0xce, 0xb6, 0xf0, 0x9b, 0x8f, 0x07, 0x5c, 0x7b, 0xa2, 0x36, 0x8f, 0x12,
	0x2c, 0x0a, 0x54, 0x2d, 0xd5, 0xcd, 0x87, 0xa3, 0x68, 0x8c, 0xff, 0x40, 0x62, 0xa2, 0x02, 0x0c,
	0x6f, 0xb1, 0x77, 0x7f, 0xcf, 0x09, 0x99, 0x63, 0x0a, 0x8f, 0x6e, 0x17, 0x7a, 0x4b, 0x08, 0x2f,
	0xc5, 0x12, 0x2a, 0x2d, 0x50, 0xf9, 0xbd, 0x51, 0x6f, 0x7c, 0x1d, 0xfe, 0x57, 0xa1, 0x94, 0x5c,
	0xe6, 0x42, 0xa5, 0xfe, 0xb9, 0xfb, 0xe3, 0x62, 0xfa, 0x8d, 0x78, 0x96, 0x30, 0xe5, 0x86, 0xfb,
	0x17, 0xa3, 0xde, 0x78, 0x38, 0x7d, 0xcf, 0x0e, 0xc4, 0xec, 0x94, 0xb0, 0x85, 0xdb, 0x60, 0x06,
	0x86, 0x87, 0xbb, 0x2e, 0xfa, 0x96, 0x5c, 0x0b, 0x25, 0x4c, 0xb4, 0x12, 0x12, 0xfc, 0x4b, 0x4b,
	0xfd, 0x74, 0x16, 0x7a, 0xb6, 0xf4, 0x43, 0x48, 0xa0, 0x73, 0x42, 0x61, 0x63, 0xa0, 0x52, 0x5c,
	0x46, 0x7b, 0xdc, 0x95, 0x1b, 0x75, 0x7b, 0x7c, 0x94, 0xed, 0x7d, 0x3a, 0x0b, 0x5f, 0x6d, 0x7b,
	0x9f, 0xb7, 0x7c, 0x5f, 0x89, 0x07, 0xaa, 0x89, 0x1a, 0x5e, 0x69, 0xbf, 0x3f, 0xba, 0x18, 0x0f,
	0xa7, 0xef, 0xd8, 0x09, 0xf7, 0xd9, 0x77, 0xd5, 0x2c, 0x79, 0x15, 0x0e, 0xc0, 0x7d, 0x35, 0xfd,
	0x42, 0x3c, 0xd4, 0x91, 0x28, 0x78, 0x06, 0xfe, 0xe0, 0x25, 0x5b, 0x84, 0x03, 0xd4, 0xcf, 0x16,
	0xfe, 0x30, 0xec, 0x94, 0x5a, 0xd9, 0x77, 0x53, 0xd2, 0x6f, 0xa9, 0xad, 0xad, 0x8a, 0x17, 0xd0,
	0x19, 0xee, 0x62, 0xfa, 0x9a, 0x5c, 0x35, 0x5c, 0xd6, 0xd0, 0x79, 0xdd, 0x26, 0x0f, 0x8b, 0xdf,
	0xb3, 0x4c, 0x98, 0x75, 0x1d, 0xb3, 0x04, 0x8b, 0xe0, 0x27, 0x62, 0x26, 0xe1, 0x51, 0x62, 0x9d,
	0xfe, 0x92, 0xdc, 0xac, 0xb0, 0x2a, 0x82, 0xfc, 0xb3, 0x9e, 0x24, 0xb2, 0xd6, 0x06, 0xaa, 0x49,
	0xf7, 0xfe, 0x27, 0x2e, 0x31, 0xee, 0xbb, 0x3b, 0xf8, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0xdd, 0x7b, 0x41, 0xaf, 0x02, 0x00, 0x00,
}
