// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundleext/v1alpha1/patch_template.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundleext/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A collection of PatcheTemplates that apply to a specific object.
type PatchCollection struct {
	Patches              []*PatchTemplate `protobuf:"bytes,1,rep,name=patches,proto3" json:"patches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PatchCollection) Reset()         { *m = PatchCollection{} }
func (m *PatchCollection) String() string { return proto.CompactTextString(m) }
func (*PatchCollection) ProtoMessage()    {}
func (*PatchCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_e12aa8cd112262b0, []int{0}
}
func (m *PatchCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCollection.Unmarshal(m, b)
}
func (m *PatchCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCollection.Marshal(b, m, deterministic)
}
func (m *PatchCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCollection.Merge(m, src)
}
func (m *PatchCollection) XXX_Size() int {
	return xxx_messageInfo_PatchCollection.Size(m)
}
func (m *PatchCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCollection.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCollection proto.InternalMessageInfo

func (m *PatchCollection) GetPatches() []*PatchTemplate {
	if m != nil {
		return m.Patches
	}
	return nil
}

// Patch provides functionality for patching Kubernetes objects. This relies on
// the strategic merge patch functionality from kubernetes.
type PatchTemplate struct {
	// Required. Name provides an identifier for this patch.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Kubernetes object reference for a custom resource that provides the
	// options (parameters) for this Patch.
	ObjectRef *ObjectReference `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	// Required. The patch itself. A templated YAML that's meant to be applied
	// viastrategic-merge-patch.  The patch itself must be specified as a
	// Go-Templatized YAML.
	TemplateString string `protobuf:"bytes,3,opt,name=template_string,json=templateString,proto3" json:"template_string,omitempty"`
	// Whether this patch is required (or optional) to be applied.
	IsRequired           bool     `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchTemplate) Reset()         { *m = PatchTemplate{} }
func (m *PatchTemplate) String() string { return proto.CompactTextString(m) }
func (*PatchTemplate) ProtoMessage()    {}
func (*PatchTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e12aa8cd112262b0, []int{1}
}
func (m *PatchTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchTemplate.Unmarshal(m, b)
}
func (m *PatchTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchTemplate.Marshal(b, m, deterministic)
}
func (m *PatchTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchTemplate.Merge(m, src)
}
func (m *PatchTemplate) XXX_Size() int {
	return xxx_messageInfo_PatchTemplate.Size(m)
}
func (m *PatchTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_PatchTemplate proto.InternalMessageInfo

func (m *PatchTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchTemplate) GetObjectRef() *ObjectReference {
	if m != nil {
		return m.ObjectRef
	}
	return nil
}

func (m *PatchTemplate) GetTemplateString() string {
	if m != nil {
		return m.TemplateString
	}
	return ""
}

func (m *PatchTemplate) GetIsRequired() bool {
	if m != nil {
		return m.IsRequired
	}
	return false
}

// Object reference for Kubernetes types. For example, if a Kubernetes
// object begins with:
//
//   apiVersion: apps/v1
//   kind: StatefulSet
//   metadata: ...
//     name: foo
//   spec: ...
//
// The corresponding ObjectReferenc (or ObjectRef) would be:
//
//   {apiVersion: 'apps/v1', kind: 'StatefulSet', name: 'foo'}
type ObjectReference struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectReference) Reset()         { *m = ObjectReference{} }
func (m *ObjectReference) String() string { return proto.CompactTextString(m) }
func (*ObjectReference) ProtoMessage()    {}
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_e12aa8cd112262b0, []int{2}
}
func (m *ObjectReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectReference.Unmarshal(m, b)
}
func (m *ObjectReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectReference.Marshal(b, m, deterministic)
}
func (m *ObjectReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectReference.Merge(m, src)
}
func (m *ObjectReference) XXX_Size() int {
	return xxx_messageInfo_ObjectReference.Size(m)
}
func (m *ObjectReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectReference.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectReference proto.InternalMessageInfo

func (m *ObjectReference) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ObjectReference) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ObjectReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PatchCollection)(nil), "pkg.apis.bundleext.v1alpha1.PatchCollection")
	proto.RegisterType((*PatchTemplate)(nil), "pkg.apis.bundleext.v1alpha1.PatchTemplate")
	proto.RegisterType((*ObjectReference)(nil), "pkg.apis.bundleext.v1alpha1.ObjectReference")
}

func init() {
	proto.RegisterFile("pkg/apis/bundleext/v1alpha1/patch_template.proto", fileDescriptor_e12aa8cd112262b0)
}

var fileDescriptor_e12aa8cd112262b0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0x86, 0x95, 0x6d, 0xb5, 0xbb, 0x75, 0xb5, 0x5b, 0x29, 0xa7, 0x48, 0x1c, 0x88, 0x7a, 0x21,
	0x42, 0xd4, 0xa6, 0xe5, 0xc2, 0x99, 0x22, 0x71, 0x40, 0xa8, 0x95, 0x41, 0x20, 0xf5, 0x12, 0x39,
	0xc9, 0x34, 0x35, 0x71, 0x6c, 0x63, 0x3b, 0x15, 0xcf, 0xc6, 0xd3, 0xa1, 0xb8, 0x4d, 0x11, 0x1c,
	0x7a, 0x1b, 0xfd, 0xc9, 0x37, 0xbf, 0x3e, 0x0f, 0xba, 0xd4, 0x55, 0x49, 0x98, 0xe6, 0x96, 0x64,
	0x8d, 0x2c, 0x04, 0xc0, 0xbb, 0x23, 0xdb, 0x29, 0x13, 0x7a, 0xc3, 0xa6, 0x44, 0x33, 0x97, 0x6f,
	0x52, 0x07, 0xb5, 0x16, 0xcc, 0x01, 0xd6, 0x46, 0x39, 0x15, 0x9e, 0xe8, 0xaa, 0xc4, 0x2d, 0x81,
	0x0f, 0x04, 0xee, 0x88, 0xf1, 0x0b, 0x1a, 0x2d, 0x5b, 0x68, 0xae, 0x84, 0x80, 0xdc, 0x71, 0x25,
	0xc3, 0x5b, 0xf4, 0xc7, 0xef, 0x01, 0x1b, 0x05, 0x71, 0x2f, 0x19, 0xce, 0xce, 0xf1, 0x91, 0x0d,
	0xd8, 0xe3, 0x4f, 0xfb, 0x4a, 0xda, 0xa1, 0xe3, 0x8f, 0x00, 0xfd, 0xfb, 0xf6, 0x29, 0x0c, 0x51,
	0x5f, 0xb2, 0x1a, 0xa2, 0x20, 0x0e, 0x92, 0x01, 0xf5, 0x73, 0x78, 0x8f, 0x90, 0xca, 0x5e, 0x21,
	0x77, 0xa9, 0x81, 0x75, 0xf4, 0x2b, 0x0e, 0x92, 0xe1, 0xec, 0xe2, 0x68, 0xdd, 0xc2, 0xff, 0x4e,
	0x61, 0x0d, 0x06, 0x64, 0x0e, 0x74, 0xa0, 0xba, 0x20, 0x3c, 0x43, 0xa3, 0x4e, 0x3d, 0xb5, 0xce,
	0x70, 0x59, 0x46, 0x3d, 0xdf, 0xf5, 0xbf, 0x8b, 0x1f, 0x7d, 0x1a, 0x9e, 0xa2, 0x21, 0xb7, 0xa9,
	0x81, 0xb7, 0x86, 0x1b, 0x28, 0xa2, 0x7e, 0x1c, 0x24, 0x7f, 0x29, 0xe2, 0x96, 0xee, 0x93, 0xf1,
	0x0a, 0x8d, 0x7e, 0xf4, 0xb4, 0x0c, 0xd3, 0x3c, 0xdd, 0x82, 0xb1, 0x5c, 0xc9, 0xbd, 0x04, 0x62,
	0x9a, 0x3f, 0xef, 0x92, 0x56, 0xaf, 0xe2, 0xb2, 0xf0, 0x12, 0x03, 0xea, 0xe7, 0x83, 0x72, 0xef,
	0x4b, 0xf9, 0x66, 0xb1, 0x7a, 0x28, 0xb9, 0xdb, 0x34, 0x19, 0xce, 0x55, 0x4d, 0xee, 0x94, 0x2a,
	0x05, 0xcc, 0x85, 0x6a, 0x8a, 0xa5, 0x60, 0x6e, 0xad, 0x4c, 0x4d, 0xaa, 0x6b, 0x3b, 0xc9, 0x45,
	0x63, 0x1d, 0x98, 0xc9, 0xee, 0x05, 0xc8, 0x91, 0xa3, 0x67, 0xbf, 0xfd, 0x99, 0xaf, 0x3e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x2f, 0x61, 0x91, 0x1a, 0x02, 0x00, 0x00,
}
