// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/application_bundle.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Kubernetes application, either run statically by the Kubelet or run by the
// K8S Control Plane.
type ClusterApplication struct {
	// Name of this cluster application. Each cluster application in the bundle
	// should have a unique name. For an example you might have a 'kube-apiserver'
	// application or perhaps even a 'kubernetes' application.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Structured Kubenetes objects that run as part of this app, whether on the
	// master, on the nodes, or in some other fashion. There is no ordering
	// guarantee for when these objects are deployed (they can be deployed in any
	// order to the cluster).
	ClusterObjects       []*ClusterObject `protobuf:"bytes,2,rep,name=cluster_objects,json=clusterObjects,proto3" json:"cluster_objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClusterApplication) Reset()         { *m = ClusterApplication{} }
func (m *ClusterApplication) String() string { return proto.CompactTextString(m) }
func (*ClusterApplication) ProtoMessage()    {}
func (*ClusterApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ef214343f7116a3, []int{0}
}
func (m *ClusterApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterApplication.Unmarshal(m, b)
}
func (m *ClusterApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterApplication.Marshal(b, m, deterministic)
}
func (m *ClusterApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterApplication.Merge(m, src)
}
func (m *ClusterApplication) XXX_Size() int {
	return xxx_messageInfo_ClusterApplication.Size(m)
}
func (m *ClusterApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterApplication.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterApplication proto.InternalMessageInfo

func (m *ClusterApplication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterApplication) GetClusterObjects() []*ClusterObject {
	if m != nil {
		return m.ClusterObjects
	}
	return nil
}

// A Kubernetes object of unspecified type.
type ClusterObject struct {
	// The name of this cluster object. This must be unique within the Cluster
	// Application.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A Kubernetes object that's untyped but which has YAML-structure. These have
	// historically been called 'YAMLs' or 'Manifests'. You might expect
	// Kubernetes objects like pods, deployments, or daemonsets to live here.
	//
	// Types that are valid to be assigned to KubeData:
	//	*ClusterObject_Inlined
	//	*ClusterObject_File
	KubeData isClusterObject_KubeData `protobuf_oneof:"kube_data"`
	// Overlays for this cluster object, which allow specialization/customization
	// of the cluster via strategic merge patch.
	//
	// Types that are valid to be assigned to OverlayData:
	//	*ClusterObject_OverlayCollection
	//	*ClusterObject_OverlayFile
	OverlayData          isClusterObject_OverlayData `protobuf_oneof:"overlay_data"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ClusterObject) Reset()         { *m = ClusterObject{} }
func (m *ClusterObject) String() string { return proto.CompactTextString(m) }
func (*ClusterObject) ProtoMessage()    {}
func (*ClusterObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ef214343f7116a3, []int{1}
}
func (m *ClusterObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterObject.Unmarshal(m, b)
}
func (m *ClusterObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterObject.Marshal(b, m, deterministic)
}
func (m *ClusterObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterObject.Merge(m, src)
}
func (m *ClusterObject) XXX_Size() int {
	return xxx_messageInfo_ClusterObject.Size(m)
}
func (m *ClusterObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterObject.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterObject proto.InternalMessageInfo

func (m *ClusterObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isClusterObject_KubeData interface {
	isClusterObject_KubeData()
}

type ClusterObject_Inlined struct {
	Inlined *_struct.Struct `protobuf:"bytes,2,opt,name=inlined,proto3,oneof"`
}

type ClusterObject_File struct {
	File *File `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

func (*ClusterObject_Inlined) isClusterObject_KubeData() {}

func (*ClusterObject_File) isClusterObject_KubeData() {}

func (m *ClusterObject) GetKubeData() isClusterObject_KubeData {
	if m != nil {
		return m.KubeData
	}
	return nil
}

func (m *ClusterObject) GetInlined() *_struct.Struct {
	if x, ok := m.GetKubeData().(*ClusterObject_Inlined); ok {
		return x.Inlined
	}
	return nil
}

func (m *ClusterObject) GetFile() *File {
	if x, ok := m.GetKubeData().(*ClusterObject_File); ok {
		return x.File
	}
	return nil
}

type isClusterObject_OverlayData interface {
	isClusterObject_OverlayData()
}

type ClusterObject_OverlayCollection struct {
	OverlayCollection *OverlayCollection `protobuf:"bytes,4,opt,name=overlay_collection,json=overlayCollection,proto3,oneof"`
}

type ClusterObject_OverlayFile struct {
	OverlayFile *File `protobuf:"bytes,5,opt,name=overlay_file,json=overlayFile,proto3,oneof"`
}

func (*ClusterObject_OverlayCollection) isClusterObject_OverlayData() {}

func (*ClusterObject_OverlayFile) isClusterObject_OverlayData() {}

func (m *ClusterObject) GetOverlayData() isClusterObject_OverlayData {
	if m != nil {
		return m.OverlayData
	}
	return nil
}

func (m *ClusterObject) GetOverlayCollection() *OverlayCollection {
	if x, ok := m.GetOverlayData().(*ClusterObject_OverlayCollection); ok {
		return x.OverlayCollection
	}
	return nil
}

func (m *ClusterObject) GetOverlayFile() *File {
	if x, ok := m.GetOverlayData().(*ClusterObject_OverlayFile); ok {
		return x.OverlayFile
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClusterObject) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClusterObject_OneofMarshaler, _ClusterObject_OneofUnmarshaler, _ClusterObject_OneofSizer, []interface{}{
		(*ClusterObject_Inlined)(nil),
		(*ClusterObject_File)(nil),
		(*ClusterObject_OverlayCollection)(nil),
		(*ClusterObject_OverlayFile)(nil),
	}
}

func _ClusterObject_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClusterObject)
	// kube_data
	switch x := m.KubeData.(type) {
	case *ClusterObject_Inlined:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Inlined); err != nil {
			return err
		}
	case *ClusterObject_File:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.File); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClusterObject.KubeData has unexpected type %T", x)
	}
	// overlay_data
	switch x := m.OverlayData.(type) {
	case *ClusterObject_OverlayCollection:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OverlayCollection); err != nil {
			return err
		}
	case *ClusterObject_OverlayFile:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OverlayFile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClusterObject.OverlayData has unexpected type %T", x)
	}
	return nil
}

func _ClusterObject_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClusterObject)
	switch tag {
	case 2: // kube_data.inlined
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(_struct.Struct)
		err := b.DecodeMessage(msg)
		m.KubeData = &ClusterObject_Inlined{msg}
		return true, err
	case 3: // kube_data.file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.KubeData = &ClusterObject_File{msg}
		return true, err
	case 4: // overlay_data.overlay_collection
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OverlayCollection)
		err := b.DecodeMessage(msg)
		m.OverlayData = &ClusterObject_OverlayCollection{msg}
		return true, err
	case 5: // overlay_data.overlay_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.OverlayData = &ClusterObject_OverlayFile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClusterObject_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClusterObject)
	// kube_data
	switch x := m.KubeData.(type) {
	case *ClusterObject_Inlined:
		s := proto.Size(x.Inlined)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClusterObject_File:
		s := proto.Size(x.File)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// overlay_data
	switch x := m.OverlayData.(type) {
	case *ClusterObject_OverlayCollection:
		s := proto.Size(x.OverlayCollection)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClusterObject_OverlayFile:
		s := proto.Size(x.OverlayFile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ClusterApplication)(nil), "pkg.apis.bundle.v1alpha1.ClusterApplication")
	proto.RegisterType((*ClusterObject)(nil), "pkg.apis.bundle.v1alpha1.ClusterObject")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/application_bundle.proto", fileDescriptor_9ef214343f7116a3)
}

var fileDescriptor_9ef214343f7116a3 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0xf3, 0x30,
	0x18, 0x85, 0xd7, 0x6d, 0xdf, 0x27, 0x4b, 0x75, 0x62, 0x6e, 0x2c, 0x43, 0x64, 0xec, 0x42, 0x07,
	0xba, 0x84, 0x6d, 0x5e, 0x78, 0xeb, 0x0a, 0x3a, 0x44, 0xd8, 0xa8, 0x77, 0x22, 0x94, 0x34, 0xcd,
	0xba, 0xd8, 0xb4, 0x29, 0x6d, 0x3a, 0xd0, 0x1f, 0xe9, 0x6f, 0x92, 0xa5, 0xad, 0x53, 0xb1, 0xe0,
	0x5d, 0xdf, 0xf4, 0x39, 0x27, 0xa7, 0xa7, 0x2f, 0x18, 0x27, 0x61, 0x80, 0x49, 0xc2, 0x33, 0xec,
	0xe5, 0xb1, 0x2f, 0x18, 0xde, 0x8c, 0x89, 0x48, 0xd6, 0x64, 0x8c, 0x49, 0x92, 0x08, 0x4e, 0x89,
	0xe2, 0x32, 0x76, 0x8b, 0x77, 0x28, 0x49, 0xa5, 0x92, 0xd0, 0x4a, 0xc2, 0x00, 0x6d, 0x25, 0xa8,
	0x3c, 0xae, 0x24, 0xbd, 0x93, 0x40, 0xca, 0x40, 0x30, 0xac, 0x39, 0x2f, 0x5f, 0xe1, 0x4c, 0xa5,
	0x39, 0x55, 0x85, 0xae, 0x77, 0x59, 0x7b, 0x55, 0x31, 0xbb, 0x54, 0x46, 0x91, 0x8c, 0x4b, 0xfa,
	0xac, 0x96, 0x96, 0x1b, 0x96, 0x0a, 0xf2, 0x5a, 0x70, 0x83, 0x37, 0x00, 0x6d, 0x91, 0x67, 0x8a,
	0xa5, 0x37, 0xbb, 0xc0, 0x10, 0x82, 0x76, 0x4c, 0x22, 0x66, 0x19, 0x7d, 0x63, 0xd8, 0x71, 0xf4,
	0x33, 0x5c, 0x82, 0x43, 0x5a, 0x90, 0xae, 0xf4, 0x5e, 0x18, 0x55, 0x99, 0xd5, 0xec, 0xb7, 0x86,
	0xe6, 0xe4, 0x1c, 0xd5, 0x7d, 0x11, 0x2a, 0xad, 0x17, 0x9a, 0x77, 0xba, 0xf4, 0xeb, 0x98, 0x0d,
	0xde, 0x9b, 0xe0, 0xe0, 0x1b, 0xf1, 0xeb, 0xbd, 0x53, 0xb0, 0xc7, 0x63, 0xc1, 0x63, 0xe6, 0x5b,
	0xcd, 0xbe, 0x31, 0x34, 0x27, 0xc7, 0xa8, 0xe8, 0x09, 0x55, 0x3d, 0xa1, 0x47, 0xdd, 0xd3, 0xbc,
	0xe1, 0x54, 0x24, 0xbc, 0x02, 0xed, 0x15, 0x17, 0xcc, 0x6a, 0x69, 0xc5, 0x69, 0x7d, 0xc2, 0x5b,
	0x2e, 0xd8, 0xbc, 0xe1, 0x68, 0x1a, 0x3e, 0x03, 0x58, 0xb6, 0xe3, 0x52, 0x29, 0x04, 0xa3, 0xdb,
	0x32, 0xac, 0xb6, 0xf6, 0xb8, 0xa8, 0xf7, 0x58, 0x14, 0x1a, 0xfb, 0x53, 0x32, 0x37, 0x9c, 0x23,
	0xf9, 0xf3, 0x10, 0xda, 0x60, 0xbf, 0x72, 0xd7, 0xd9, 0xfe, 0xfd, 0x29, 0x9b, 0xe1, 0x98, 0xa5,
	0x6a, 0x3b, 0xce, 0x4c, 0xd0, 0x09, 0x73, 0x8f, 0xb9, 0x3e, 0x51, 0x64, 0xd6, 0xdd, 0x39, 0xea,
	0xf9, 0xe1, 0xe9, 0x3e, 0xe0, 0x6a, 0x9d, 0x7b, 0x88, 0xca, 0x08, 0xdf, 0xe9, 0x96, 0x6c, 0x21,
	0x73, 0x7f, 0x29, 0x88, 0x5a, 0xc9, 0x34, 0xc2, 0xe1, 0x75, 0x36, 0x2a, 0xff, 0xc2, 0xa8, 0x5c,
	0x8c, 0xba, 0x45, 0xf1, 0xfe, 0xeb, 0x7e, 0xa7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe3,
	0xd4, 0xc8, 0xe4, 0x02, 0x00, 0x00,
}
