// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/bundle_common.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File represents some sort of file that's specified external to the bundle,
// which could be on either a local or remote file system.
type File struct {
	// Url to find this file.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional Sha256 hash of the binary to ensure we are pulling the correct
	// binary/file.
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Object reference for Kubernetes types. For example, if a Kubernetes
// object begins with:
//
//   apiVersion: apps/v1
//   kind: StatefulSet
//   metadata: ...
//     name: foo
//   spec: ...
//
// The corresponding GroupVersionKind (or GVK) would be:
//
//   {apiVersion: 'apps/v1', kind: 'StatefulSet', name: 'foo'}
type ObjectReference struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectReference) Reset()         { *m = ObjectReference{} }
func (m *ObjectReference) String() string { return proto.CompactTextString(m) }
func (*ObjectReference) ProtoMessage()    {}
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{1}
}

func (m *ObjectReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectReference.Unmarshal(m, b)
}
func (m *ObjectReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectReference.Marshal(b, m, deterministic)
}
func (m *ObjectReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectReference.Merge(m, src)
}
func (m *ObjectReference) XXX_Size() int {
	return xxx_messageInfo_ObjectReference.Size(m)
}
func (m *ObjectReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectReference.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectReference proto.InternalMessageInfo

func (m *ObjectReference) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ObjectReference) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ObjectReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A key for retrieving a specific cluster object.
type ClusterObjectKey struct {
	// Name of the cluster component.
	ComponentName string `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// Name of the cluster object within the component.
	ObjectName           string   `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterObjectKey) Reset()         { *m = ClusterObjectKey{} }
func (m *ClusterObjectKey) String() string { return proto.CompactTextString(m) }
func (*ClusterObjectKey) ProtoMessage()    {}
func (*ClusterObjectKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{2}
}

func (m *ClusterObjectKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterObjectKey.Unmarshal(m, b)
}
func (m *ClusterObjectKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterObjectKey.Marshal(b, m, deterministic)
}
func (m *ClusterObjectKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterObjectKey.Merge(m, src)
}
func (m *ClusterObjectKey) XXX_Size() int {
	return xxx_messageInfo_ClusterObjectKey.Size(m)
}
func (m *ClusterObjectKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterObjectKey.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterObjectKey proto.InternalMessageInfo

func (m *ClusterObjectKey) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *ClusterObjectKey) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "pkg.apis.bundle.v1alpha1.File")
	proto.RegisterType((*ObjectReference)(nil), "pkg.apis.bundle.v1alpha1.ObjectReference")
	proto.RegisterType((*ClusterObjectKey)(nil), "pkg.apis.bundle.v1alpha1.ClusterObjectKey")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/bundle_common.proto", fileDescriptor_86b0256555baa44c)
}

var fileDescriptor_86b0256555baa44c = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x99, 0x1b, 0x82, 0x11, 0x75, 0xe4, 0xd4, 0x9b, 0x52, 0x10, 0x3c, 0x6c, 0x2d, 0xc3,
	0x8b, 0x67, 0x07, 0x0a, 0x2a, 0x2a, 0x3b, 0x78, 0xe8, 0xa5, 0xa4, 0xe9, 0xb7, 0x36, 0x36, 0xc9,
	0x17, 0xd2, 0x64, 0xe0, 0x7f, 0x2f, 0x49, 0x3a, 0x6f, 0xde, 0x5e, 0x7f, 0x7d, 0xdf, 0x7b, 0xe1,
	0x91, 0x95, 0x19, 0xba, 0x92, 0x19, 0x31, 0x96, 0x8d, 0xd7, 0xad, 0x84, 0xf2, 0xb0, 0x61, 0xd2,
	0xf4, 0x6c, 0x33, 0x7d, 0xd7, 0x1c, 0x95, 0x42, 0x5d, 0x18, 0x8b, 0x0e, 0x69, 0x66, 0x86, 0xae,
	0x08, 0xee, 0x22, 0xfd, 0x2d, 0x8e, 0xee, 0x7c, 0x45, 0x16, 0x4f, 0x42, 0x02, 0x5d, 0x92, 0xb9,
	0xb7, 0x32, 0x9b, 0xdd, 0xcc, 0xee, 0xce, 0x76, 0x41, 0x52, 0x4a, 0x16, 0x3d, 0x1b, 0xfb, 0xec,
	0x24, 0xa2, 0xa8, 0xf3, 0x8a, 0x5c, 0x7d, 0x34, 0xdf, 0xc0, 0xdd, 0x0e, 0xf6, 0x60, 0x41, 0x73,
	0xa0, 0xd7, 0xe4, 0x9c, 0x19, 0x51, 0x1f, 0xc0, 0x8e, 0x02, 0xf5, 0x14, 0x40, 0x98, 0x11, 0x5f,
	0x89, 0x84, 0x9c, 0x41, 0xe8, 0xf6, 0x98, 0x13, 0x74, 0x60, 0x9a, 0x29, 0xc8, 0xe6, 0x89, 0x05,
	0x9d, 0x57, 0x64, 0xb9, 0x95, 0x7e, 0x74, 0x60, 0x53, 0xc5, 0x2b, 0xfc, 0xd0, 0x5b, 0x72, 0xc9,
	0x51, 0x19, 0xd4, 0xa0, 0x5d, 0x1d, 0x2f, 0x52, 0xfe, 0xc5, 0x1f, 0x7d, 0x67, 0x2a, 0xbe, 0x01,
	0xe3, 0x4d, 0xf2, 0xa4, 0x26, 0x92, 0x50, 0x30, 0x3c, 0xbe, 0x55, 0x2f, 0x9d, 0x70, 0xbd, 0x6f,
	0x0a, 0x8e, 0xaa, 0x7c, 0x46, 0xec, 0x24, 0x6c, 0x25, 0xfa, 0xf6, 0x53, 0x32, 0xb7, 0x47, 0xab,
	0xca, 0xe1, 0x61, 0x5c, 0xf3, 0x54, 0xbf, 0x9e, 0x16, 0xfd, 0x6f, 0xe1, 0xe6, 0x34, 0x8e, 0x7a,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xa8, 0x07, 0x65, 0x84, 0x01, 0x00, 0x00,
}
