// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/bundle_common.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File represents some sort of file that's specified external to the bundle,
// which could be on either a local or remote file system.
type File struct {
	// Path to find this file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional Sha256 hash of the binary to ensure we are pulling the correct
	// binary/file.
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Group-version-kind wrapper for Kubernetes types. For example, if a Kubernetes
// object begins with:
//
//   apiVersion: apps/v1
//   kind: StatefulSet
//   metadata: ...
//   spec: ...
//
// The corresponding GroupVersionKind (or GVK) would be:
//
//   {group: 'apps', version: 'v1', kind: 'StatefulSet'}
type GroupVersionKind struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupVersionKind) Reset()         { *m = GroupVersionKind{} }
func (m *GroupVersionKind) String() string { return proto.CompactTextString(m) }
func (*GroupVersionKind) ProtoMessage()    {}
func (*GroupVersionKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{1}
}
func (m *GroupVersionKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupVersionKind.Unmarshal(m, b)
}
func (m *GroupVersionKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupVersionKind.Marshal(b, m, deterministic)
}
func (m *GroupVersionKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupVersionKind.Merge(m, src)
}
func (m *GroupVersionKind) XXX_Size() int {
	return xxx_messageInfo_GroupVersionKind.Size(m)
}
func (m *GroupVersionKind) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupVersionKind.DiscardUnknown(m)
}

var xxx_messageInfo_GroupVersionKind proto.InternalMessageInfo

func (m *GroupVersionKind) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GroupVersionKind) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GroupVersionKind) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

// A key for retrieving a specific cluster object.
type ClusterObjectKey struct {
	// Name of the cluster application.
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Name of the cluster object within the application.
	ObjectName           string   `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterObjectKey) Reset()         { *m = ClusterObjectKey{} }
func (m *ClusterObjectKey) String() string { return proto.CompactTextString(m) }
func (*ClusterObjectKey) ProtoMessage()    {}
func (*ClusterObjectKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{2}
}
func (m *ClusterObjectKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterObjectKey.Unmarshal(m, b)
}
func (m *ClusterObjectKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterObjectKey.Marshal(b, m, deterministic)
}
func (m *ClusterObjectKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterObjectKey.Merge(m, src)
}
func (m *ClusterObjectKey) XXX_Size() int {
	return xxx_messageInfo_ClusterObjectKey.Size(m)
}
func (m *ClusterObjectKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterObjectKey.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterObjectKey proto.InternalMessageInfo

func (m *ClusterObjectKey) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ClusterObjectKey) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "pkg.apis.bundle.v1alpha1.File")
	proto.RegisterType((*GroupVersionKind)(nil), "pkg.apis.bundle.v1alpha1.GroupVersionKind")
	proto.RegisterType((*ClusterObjectKey)(nil), "pkg.apis.bundle.v1alpha1.ClusterObjectKey")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/bundle_common.proto", fileDescriptor_86b0256555baa44c)
}

var fileDescriptor_86b0256555baa44c = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x55, 0x28, 0x14, 0x8e, 0xa5, 0xb2, 0x18, 0xc2, 0x04, 0xca, 0xc4, 0x40, 0x1d, 0x55,
	0x2c, 0xcc, 0x54, 0xa2, 0x12, 0x45, 0x05, 0x31, 0x74, 0x60, 0xa9, 0x2e, 0x89, 0x49, 0x4c, 0x6c,
	0xdf, 0x29, 0x71, 0x2a, 0xf1, 0xef, 0x91, 0xe3, 0x74, 0x64, 0x7b, 0xef, 0xf9, 0xf3, 0x3b, 0xe9,
	0xc1, 0x03, 0x37, 0x55, 0x86, 0xac, 0xbb, 0x2c, 0xef, 0x5d, 0x69, 0x54, 0x76, 0x58, 0xa2, 0xe1,
	0x1a, 0x97, 0xa3, 0xdf, 0x17, 0x64, 0x2d, 0x39, 0xc9, 0x2d, 0x79, 0x12, 0x09, 0x37, 0x95, 0x0c,
	0xb4, 0x8c, 0xaf, 0xf2, 0x48, 0xa7, 0x12, 0xa6, 0x2f, 0xda, 0x28, 0x21, 0x60, 0xca, 0xe8, 0xeb,
	0x64, 0x72, 0x37, 0xb9, 0xbf, 0xfc, 0x1c, 0x74, 0xc8, 0x6a, 0xec, 0xea, 0xe4, 0x24, 0x66, 0x41,
	0xa7, 0x3b, 0x98, 0xaf, 0x5b, 0xea, 0x79, 0xa7, 0xda, 0x4e, 0x93, 0xdb, 0x68, 0x57, 0x8a, 0x6b,
	0x38, 0xab, 0x42, 0x36, 0x7e, 0x8e, 0x46, 0x24, 0x30, 0x3b, 0x44, 0x68, 0x2c, 0x38, 0xda, 0xd0,
	0xdb, 0x68, 0x57, 0x26, 0xa7, 0xb1, 0x37, 0xe8, 0x74, 0x0b, 0xf3, 0x95, 0xe9, 0x3b, 0xaf, 0xda,
	0xf7, 0xfc, 0x47, 0x15, 0x7e, 0xa3, 0x7e, 0xc5, 0x0d, 0x5c, 0x20, 0xf3, 0xde, 0xa1, 0x55, 0x63,
	0xf5, 0x0c, 0x99, 0xb7, 0x68, 0x95, 0xb8, 0x85, 0x2b, 0x1a, 0xb8, 0xf8, 0x1a, 0x0f, 0x40, 0x8c,
	0x02, 0xf0, 0xfc, 0xf6, 0xf5, 0x5a, 0x69, 0x5f, 0xf7, 0xb9, 0x2c, 0xc8, 0x66, 0x6b, 0xa2, 0xca,
	0xa8, 0x95, 0xa1, 0xbe, 0xfc, 0x30, 0xe8, 0xbf, 0xa9, 0xb5, 0x59, 0xf3, 0xd4, 0x2d, 0x8a, 0x78,
	0x72, 0x31, 0x6e, 0xf8, 0xdf, 0xa6, 0xf9, 0xf9, 0x30, 0xe3, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0x2d, 0x3c, 0xe8, 0x76, 0x01, 0x00, 0x00,
}
