// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/bundle_common.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File represents some sort of file that's specified external to the bundle,
// which could be on either a local or remote file system.
type File struct {
	// Url to find this file.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional Sha256 hash of the binary to ensure we are pulling the correct
	// binary/file.
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b0256555baa44c, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "pkg.apis.bundle.v1alpha1.File")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/bundle_common.proto", fileDescriptor_86b0256555baa44c)
}

var fileDescriptor_86b0256555baa44c = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x29, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2c, 0xc8, 0x2c, 0xd6, 0x4f, 0x2a, 0xcd, 0x4b, 0xc9, 0x49, 0xd5, 0x2f, 0x33, 0x4c, 0xcc,
	0x29, 0xc8, 0x48, 0x34, 0x84, 0xf2, 0xe3, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x24, 0x0a, 0xb2, 0xd3, 0xf5, 0x40, 0xaa, 0xf5, 0x20, 0xb2, 0x7a, 0x30,
	0xd5, 0x4a, 0x3a, 0x5c, 0x2c, 0x6e, 0x99, 0x39, 0xa9, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x45, 0x39,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x10, 0x17, 0x4b, 0x46, 0x62, 0x71,
	0x86, 0x04, 0x13, 0x58, 0x08, 0xcc, 0x76, 0xf2, 0x89, 0xf2, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x77, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0x75, 0xce, 0xc9, 0x2f, 0x4d,
	0x09, 0xc8, 0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0xcf, 0xb6, 0x28, 0xd6, 0x4d, 0xce, 0x29,
	0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x85, 0xba, 0x0c, 0x97, 0x4b, 0x93, 0xd8, 0xc0, 0x8e, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xd2, 0x96, 0xb3, 0xcc, 0x00, 0x00, 0x00,
}
