// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/cluster_bundle.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The ClusterBundle is a packaging format for Kubernetes Components.
type ClusterBundle struct {
	// Required. Kubernetes API Version for the Bundle.
	// Must be gke.io/k8s-cluster-bundle/v1alpha1.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Required. The Kubernetes `kind` for this object. Must be 'ClusterBundle'.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Required. Kubernetes ObjectMeta proto. The Metadata.name field must be
	// filled out for each Bundle.
	Metadata *ObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec for the ClusterBundle, which specifies the intended Kubernetes cluster
	// configuration.
	Spec                 *ClusterBundleSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ClusterBundle) Reset()         { *m = ClusterBundle{} }
func (m *ClusterBundle) String() string { return proto.CompactTextString(m) }
func (*ClusterBundle) ProtoMessage()    {}
func (*ClusterBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30f666a9d42204, []int{0}
}

func (m *ClusterBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterBundle.Unmarshal(m, b)
}
func (m *ClusterBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterBundle.Marshal(b, m, deterministic)
}
func (m *ClusterBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterBundle.Merge(m, src)
}
func (m *ClusterBundle) XXX_Size() int {
	return xxx_messageInfo_ClusterBundle.Size(m)
}
func (m *ClusterBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterBundle.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterBundle proto.InternalMessageInfo

func (m *ClusterBundle) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ClusterBundle) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ClusterBundle) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ClusterBundle) GetSpec() *ClusterBundleSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

// A spec object that wraps the Cluster Bundle.
type ClusterBundleSpec struct {
	// Version-string for this bundle. The version should be a SemVer string (see
	// https://semver.org/) of the form X.Y.Z (Major.Minor.Patch).  Generally
	// speaking, a major-version (changes should indicate breaking changes,
	// minor-versions should indicate backwards compatible features, and patch
	// changes should indicate backwords compatible. If there are any changes to
	// the bundle, then the version string must be incremented.
	//
	// If a bundle is versioned, then all its components must be versioned.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The release channel for this bundle, which indicates the minimum
	// stability of components in the Bundle. For example, you might have
	// 'Dev', 'Beta', or 'Stable' channels. If the channel is 'Stable' all
	// artifacts in the bundle must be labeled as 'Stable'. If a channel is
	// labeled as 'Dev' then, you may want all packages in the bundle to be at
	// least Alpha (but possibly also 'Beta' or 'Stable').
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Configuration for the nodes.
	NodeConfigs []*NodeConfig `protobuf:"bytes,3,rep,name=node_configs,json=nodeConfigs,proto3" json:"node_configs,omitempty"`
	// Configuration for the nodes, specified as external files. The process of
	// inlining reads node config files into node configs, and so after
	// inlining, this list will be empty.
	NodeConfigFiles []*File `protobuf:"bytes,4,rep,name=node_config_files,json=nodeConfigFiles,proto3" json:"node_config_files,omitempty"`
	// Kubernetes objects grouped into cluster components and versioned together.
	// These could be applications or they could be some sort of supporting
	// object collection.
	Components []*ClusterComponent `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"`
	// Cluster components that are specified externally as Files. The process of inlining
	// for a bundle reads component files into components, and so after
	// inlining, this list will be empty.
	ComponentFiles       []*File  `protobuf:"bytes,6,rep,name=component_files,json=componentFiles,proto3" json:"component_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterBundleSpec) Reset()         { *m = ClusterBundleSpec{} }
func (m *ClusterBundleSpec) String() string { return proto.CompactTextString(m) }
func (*ClusterBundleSpec) ProtoMessage()    {}
func (*ClusterBundleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30f666a9d42204, []int{1}
}

func (m *ClusterBundleSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterBundleSpec.Unmarshal(m, b)
}
func (m *ClusterBundleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterBundleSpec.Marshal(b, m, deterministic)
}
func (m *ClusterBundleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterBundleSpec.Merge(m, src)
}
func (m *ClusterBundleSpec) XXX_Size() int {
	return xxx_messageInfo_ClusterBundleSpec.Size(m)
}
func (m *ClusterBundleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterBundleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterBundleSpec proto.InternalMessageInfo

func (m *ClusterBundleSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClusterBundleSpec) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ClusterBundleSpec) GetNodeConfigs() []*NodeConfig {
	if m != nil {
		return m.NodeConfigs
	}
	return nil
}

func (m *ClusterBundleSpec) GetNodeConfigFiles() []*File {
	if m != nil {
		return m.NodeConfigFiles
	}
	return nil
}

func (m *ClusterBundleSpec) GetComponents() []*ClusterComponent {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *ClusterBundleSpec) GetComponentFiles() []*File {
	if m != nil {
		return m.ComponentFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*ClusterBundle)(nil), "pkg.apis.bundle.v1alpha1.ClusterBundle")
	proto.RegisterType((*ClusterBundleSpec)(nil), "pkg.apis.bundle.v1alpha1.ClusterBundleSpec")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/cluster_bundle.proto", fileDescriptor_6b30f666a9d42204)
}

var fileDescriptor_6b30f666a9d42204 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x95, 0x36, 0x14, 0x70, 0x81, 0xaa, 0x3e, 0x59, 0x3d, 0x40, 0x55, 0x71, 0xa8, 0x0a,
	0x4d, 0x28, 0x5c, 0xb8, 0x81, 0x1a, 0x89, 0x4a, 0x15, 0x5f, 0x0a, 0x12, 0x07, 0x2e, 0x91, 0xe3,
	0xb8, 0xa9, 0x89, 0x63, 0x5b, 0xb1, 0xd3, 0x57, 0xe4, 0x79, 0x78, 0x83, 0x55, 0x9c, 0x8f, 0x6d,
	0xb5, 0xca, 0x76, 0x6f, 0x9e, 0x99, 0xff, 0xff, 0xe7, 0x99, 0xd1, 0x80, 0xb5, 0xca, 0x52, 0x1f,
	0x2b, 0xa6, 0xfd, 0xb8, 0x14, 0x09, 0xa7, 0xfe, 0x69, 0x83, 0xb9, 0x3a, 0xe2, 0x8d, 0x4f, 0x78,
	0xa9, 0x0d, 0x2d, 0xa2, 0x3a, 0xef, 0xa9, 0x42, 0x1a, 0x09, 0x91, 0xca, 0x52, 0xaf, 0x92, 0x7b,
	0x4d, 0xba, 0x95, 0xcf, 0xde, 0xf6, 0x82, 0xea, 0x38, 0x22, 0x32, 0xcf, 0xa5, 0xa8, 0x39, 0xb3,
	0x77, 0x57, 0xbf, 0x25, 0x32, 0x57, 0x52, 0x50, 0x61, 0x1a, 0xc7, 0xaa, 0xd7, 0x21, 0x64, 0x52,
	0xd1, 0xc5, 0x81, 0xa5, 0x57, 0xb5, 0x32, 0xfe, 0x4b, 0x89, 0x89, 0x72, 0x6a, 0x70, 0xad, 0x5d,
	0xfc, 0x73, 0xc0, 0xf3, 0xa0, 0xfe, 0x73, 0x6b, 0xc5, 0xf0, 0x15, 0x18, 0x63, 0xc5, 0xa2, 0x13,
	0x2d, 0x34, 0x93, 0x02, 0x39, 0x73, 0x67, 0xf9, 0x34, 0x04, 0x58, 0xb1, 0xdf, 0x75, 0x06, 0x42,
	0xe0, 0x66, 0x4c, 0x24, 0x68, 0x60, 0x2b, 0xf6, 0x0d, 0x3f, 0x83, 0x27, 0x15, 0x34, 0xc1, 0x06,
	0xa3, 0xe1, 0xdc, 0x59, 0x8e, 0xdf, 0xbf, 0xf6, 0xfa, 0x76, 0xe5, 0xfd, 0xb0, 0x5d, 0x7c, 0xa3,
	0x06, 0x87, 0x9d, 0x0b, 0x7e, 0x02, 0xae, 0x56, 0x94, 0x20, 0xd7, 0xba, 0xdf, 0xf4, 0xbb, 0x2f,
	0xba, 0xfd, 0xa5, 0x28, 0x09, 0xad, 0x71, 0xf1, 0x7f, 0x00, 0xa6, 0x77, 0x6a, 0x10, 0x81, 0xc7,
	0x97, 0x93, 0xb4, 0x61, 0x55, 0x21, 0x47, 0x2c, 0x04, 0xe5, 0xcd, 0x24, 0x6d, 0x08, 0x77, 0xe0,
	0xd9, 0xd9, 0x52, 0x35, 0x1a, 0xce, 0x87, 0xf7, 0x0f, 0xf4, 0x5d, 0x26, 0x34, 0xb0, 0xe2, 0x70,
	0x2c, 0xba, 0xb7, 0x86, 0x7b, 0x30, 0x3d, 0x03, 0x45, 0x07, 0xc6, 0xa9, 0x46, 0xae, 0xa5, 0xbd,
	0xec, 0xa7, 0x7d, 0x61, 0x9c, 0x86, 0x93, 0x5b, 0x4e, 0x15, 0x57, 0x2c, 0xd0, 0xdd, 0x84, 0x46,
	0x8f, 0x2c, 0x64, 0x75, 0x75, 0x4b, 0x41, 0x6b, 0x09, 0xcf, 0xdc, 0x70, 0x07, 0x26, 0x5d, 0xd4,
	0x74, 0x35, 0x7a, 0x50, 0x57, 0x2f, 0x3a, 0x9b, 0x6d, 0x6a, 0xfb, 0xf5, 0xcf, 0x3e, 0x65, 0xe6,
	0x58, 0xc6, 0x1e, 0x91, 0xb9, 0xbf, 0x93, 0x32, 0xe5, 0x34, 0xe0, 0xb2, 0x4c, 0x7e, 0x72, 0x6c,
	0x0e, 0xb2, 0xc8, 0xfd, 0xec, 0xa3, 0x5e, 0x37, 0x37, 0xbd, 0x6e, 0xae, 0xb1, 0xef, 0x3a, 0xe3,
	0x91, 0x3d, 0xc9, 0x0f, 0x37, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xa6, 0x4f, 0x76, 0x95, 0x03,
	0x00, 0x00,
}
