// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/cluster_component.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Kubernetes objects grouped into cluster components and versioned together.
// These could be applications or they could be some sort of supporting
// object collection.
type ClusterComponent struct {
	// Required. Kubernetes API Version for the ClusterComponent type.
	// Must always be 'gke.io/k8s-cluster-bundle/v1alpha1'
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Required. The Kubernetes `kind` for this object. Must be
	// 'ClusterComponent'.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kubernetes Metadata for the component. The Metadata.name field must be
	// filled out and each component in a bundle must have a unique name. For
	// example you might have a 'kube-apiserver' component or perhaps even a
	// 'kubernetes' component, depending on the granulatarity of the Bundle
	// components.
	Metadata *ObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Required. Version-string for this component. The version should be a SemVer
	// 2 string (see https://semver.org/) of the form X.Y.Z (Major.Minor.Patch).
	// A major-version changes should indicate breaking changes, minor-versions
	// should indicate backwards compatible features, and patch changes should
	// indicate backwords compatible. If there are any changes to the component,
	// then the version string must be incremented.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Optional. A version-string representing the version of the API this
	// component offers to other components (for the purposes of requirement
	// satisfaction). If no API is offered to other components, then this field
	// may be blank, but then other components may not depend on this component.
	ComponentApiVersion string `protobuf:"bytes,5,opt,name=componentApiVersion,proto3" json:"componentApiVersion,omitempty"`
	// A list of components that must be packaged in a bundle in with this
	// component.
	Requirements []*MinRequirement `protobuf:"bytes,6,rep,name=requirements,proto3" json:"requirements,omitempty"`
	// Structured Kubenetes objects that run as part of this app, whether on the
	// master, on the nodes, or in some other fashio.  These Kubernetes objects
	// are inlined and must be YAML/JSON
	// compatible. Each must have `apiVersion`, `kind`, and `metadata`
	ClusterObjects []*_struct.Struct `protobuf:"bytes,7,rep,name=cluster_objects,json=clusterObjects,proto3" json:"cluster_objects,omitempty"`
	// Cluster objects that are specified via a File-URL. The process of inlining
	// the a component turns cluster object files into cluster objects.
	// During the inline process, if the file is YAML-formatted and contains multiple
	// objects, the objects will be split into separate inline objects. In other
	// words, one cluster object file may result in multiple cluster objects.
	ClusterObjectFiles   []*File  `protobuf:"bytes,8,rep,name=cluster_object_files,json=clusterObjectFiles,proto3" json:"cluster_object_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterComponent) Reset()         { *m = ClusterComponent{} }
func (m *ClusterComponent) String() string { return proto.CompactTextString(m) }
func (*ClusterComponent) ProtoMessage()    {}
func (*ClusterComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_39e88fab7b1fe3e6, []int{0}
}
func (m *ClusterComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterComponent.Unmarshal(m, b)
}
func (m *ClusterComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterComponent.Marshal(b, m, deterministic)
}
func (m *ClusterComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterComponent.Merge(m, src)
}
func (m *ClusterComponent) XXX_Size() int {
	return xxx_messageInfo_ClusterComponent.Size(m)
}
func (m *ClusterComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterComponent.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterComponent proto.InternalMessageInfo

func (m *ClusterComponent) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ClusterComponent) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ClusterComponent) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ClusterComponent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClusterComponent) GetComponentApiVersion() string {
	if m != nil {
		return m.ComponentApiVersion
	}
	return ""
}

func (m *ClusterComponent) GetRequirements() []*MinRequirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *ClusterComponent) GetClusterObjects() []*_struct.Struct {
	if m != nil {
		return m.ClusterObjects
	}
	return nil
}

func (m *ClusterComponent) GetClusterObjectFiles() []*File {
	if m != nil {
		return m.ClusterObjectFiles
	}
	return nil
}

// MinRequirement represents a component that this component must be packaged
// with in a ClusterBundle (or must be satisfied in some other fashion). This is
// roughly based on Semantic Import Versioning in the Go Language:
// https://research.swtch.com/vgo-import.
type MinRequirement struct {
	// Name of a component. The component name specified here must match exactly a
	// component name in the `metadata.name` field of another component.
	Component string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// The sem-ver apiVersion of the component. The API Version is only a minimum
	// requirement. The assumption any newer component with only backwards
	// compatable changes is acceptable.
	ComponentApiVersion  string   `protobuf:"bytes,2,opt,name=componentApiVersion,proto3" json:"componentApiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinRequirement) Reset()         { *m = MinRequirement{} }
func (m *MinRequirement) String() string { return proto.CompactTextString(m) }
func (*MinRequirement) ProtoMessage()    {}
func (*MinRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_39e88fab7b1fe3e6, []int{1}
}
func (m *MinRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinRequirement.Unmarshal(m, b)
}
func (m *MinRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinRequirement.Marshal(b, m, deterministic)
}
func (m *MinRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinRequirement.Merge(m, src)
}
func (m *MinRequirement) XXX_Size() int {
	return xxx_messageInfo_MinRequirement.Size(m)
}
func (m *MinRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_MinRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_MinRequirement proto.InternalMessageInfo

func (m *MinRequirement) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *MinRequirement) GetComponentApiVersion() string {
	if m != nil {
		return m.ComponentApiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterComponent)(nil), "pkg.apis.bundle.v1alpha1.ClusterComponent")
	proto.RegisterType((*MinRequirement)(nil), "pkg.apis.bundle.v1alpha1.MinRequirement")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/cluster_component.proto", fileDescriptor_39e88fab7b1fe3e6)
}

var fileDescriptor_39e88fab7b1fe3e6 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5f, 0xef, 0xd2, 0x30,
	0x14, 0x0d, 0x3f, 0x7e, 0xf2, 0xa7, 0x18, 0x34, 0xd5, 0xc4, 0x86, 0x10, 0x42, 0x88, 0x0f, 0x8b,
	0x91, 0x16, 0xf0, 0xc5, 0x47, 0x94, 0x44, 0x13, 0x03, 0x91, 0xcc, 0xc4, 0x07, 0x5f, 0xb0, 0xdb,
	0xca, 0xa8, 0xeb, 0xda, 0xb9, 0x76, 0x7c, 0x34, 0x3f, 0x9f, 0x59, 0xb7, 0x81, 0x4b, 0xec, 0x5b,
	0x7b, 0x7b, 0xce, 0xb9, 0xe7, 0x9e, 0x5b, 0xb0, 0xca, 0x92, 0x98, 0xd0, 0x8c, 0x6b, 0x12, 0x14,
	0x32, 0x12, 0x8c, 0x5c, 0xd7, 0x54, 0x64, 0x17, 0xba, 0x26, 0xa1, 0x28, 0xb4, 0x61, 0xf9, 0x29,
	0x54, 0x69, 0xa6, 0x24, 0x93, 0x06, 0x67, 0xb9, 0x32, 0x0a, 0xa2, 0x2c, 0x89, 0x71, 0xc9, 0xc0,
	0x15, 0x03, 0x37, 0x8c, 0xc9, 0x34, 0x56, 0x2a, 0x16, 0x8c, 0x58, 0x5c, 0x50, 0x9c, 0x89, 0x36,
	0x79, 0x11, 0xd6, 0xbc, 0xc9, 0x5b, 0x67, 0xa7, 0xea, 0x5e, 0x36, 0x4a, 0x95, 0xac, 0xd1, 0x6f,
	0x9c, 0x68, 0x15, 0xfc, 0x62, 0xa1, 0x39, 0xa5, 0xcc, 0xd0, 0x0a, 0xbb, 0xf8, 0xd3, 0x05, 0xcf,
	0x77, 0x95, 0xdb, 0x5d, 0x63, 0x16, 0xce, 0x00, 0xa0, 0x19, 0xff, 0xce, 0x72, 0xcd, 0x95, 0x44,
	0x9d, 0x79, 0xc7, 0x1b, 0xfa, 0xff, 0x54, 0x20, 0x04, 0x8f, 0x09, 0x97, 0x11, 0x7a, 0xb0, 0x2f,
	0xf6, 0x0c, 0xb7, 0x60, 0x50, 0xca, 0x46, 0xd4, 0x50, 0xd4, 0x9d, 0x77, 0xbc, 0xd1, 0xe6, 0x35,
	0x76, 0x4d, 0x8b, 0xbf, 0x5a, 0x1f, 0x07, 0x66, 0xa8, 0x7f, 0x63, 0x41, 0x04, 0xfa, 0xd7, 0xba,
	0xe5, 0xa3, 0x15, 0x6e, 0xae, 0x70, 0x05, 0x5e, 0xdc, 0x92, 0xfc, 0x70, 0x37, 0xf6, 0xc4, 0xa2,
	0xfe, 0xf7, 0x04, 0xf7, 0xe0, 0x69, 0xce, 0x7e, 0x17, 0x3c, 0x67, 0x29, 0x93, 0x46, 0xa3, 0xde,
	0xbc, 0xeb, 0x8d, 0x36, 0x9e, 0xdb, 0xd1, 0x81, 0x4b, 0xff, 0x4e, 0xf0, 0x5b, 0x6c, 0xb8, 0x05,
	0xcf, 0x9a, 0x8d, 0x56, 0x09, 0x6a, 0xd4, 0xb7, 0x82, 0xaf, 0x70, 0xb5, 0x36, 0xdc, 0xac, 0x0d,
	0x7f, 0xb3, 0x6b, 0xf3, 0xc7, 0x35, 0xbe, 0x1a, 0x54, 0xc3, 0x23, 0x78, 0xd9, 0x56, 0x38, 0x9d,
	0xb9, 0x60, 0x1a, 0x0d, 0xac, 0xcc, 0xcc, 0xed, 0xeb, 0x13, 0x17, 0xcc, 0x87, 0x2d, 0xb5, 0xb2,
	0xa4, 0x17, 0x3f, 0xc1, 0xb8, 0xed, 0x19, 0x4e, 0xc1, 0xf0, 0x16, 0x45, 0xbd, 0xb4, 0x7b, 0xc1,
	0x95, 0xe1, 0x83, 0x33, 0xc3, 0x8f, 0xfb, 0x1f, 0x5f, 0x62, 0x6e, 0x2e, 0x45, 0x80, 0x43, 0x95,
	0x92, 0xcf, 0x76, 0xd0, 0x9d, 0x50, 0x45, 0x74, 0x14, 0xd4, 0x9c, 0x55, 0x9e, 0x92, 0xe4, 0xbd,
	0x5e, 0xd6, 0xd6, 0x96, 0xf5, 0x57, 0x73, 0x7d, 0xbd, 0xa0, 0x67, 0x23, 0x7a, 0xf7, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xed, 0xc5, 0x58, 0x97, 0x35, 0x03, 0x00, 0x00,
}
