// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/component_package.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Kubernetes objects grouped into cluster components and versioned together.
// These could be applications or they could be some sort of supporting
// collection of objects.
type ComponentPackage struct {
	// Required. Kubernetes API Version for the ComponentPackage type.
	// Must always be 'bundle.gke.io/v1alpha1'
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Required. The Kubernetes `kind` for this object. Must be
	// 'ComponentPackage'.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kubernetes Metadata for the component. The Metadata.name field must be
	// filled out and each component in a bundle must have a unique name. For
	// example you might have a 'kube-apiserver' component or perhaps even a
	// 'kubernetes' component, depending on the granularity of the Bundle
	// components.
	Metadata *ObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec for the ComponentPackage.
	Spec                 *ComponentPackageSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ComponentPackage) Reset()         { *m = ComponentPackage{} }
func (m *ComponentPackage) String() string { return proto.CompactTextString(m) }
func (*ComponentPackage) ProtoMessage()    {}
func (*ComponentPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_500109098fa4d83a, []int{0}
}

func (m *ComponentPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentPackage.Unmarshal(m, b)
}
func (m *ComponentPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentPackage.Marshal(b, m, deterministic)
}
func (m *ComponentPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentPackage.Merge(m, src)
}
func (m *ComponentPackage) XXX_Size() int {
	return xxx_messageInfo_ComponentPackage.Size(m)
}
func (m *ComponentPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentPackage.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentPackage proto.InternalMessageInfo

func (m *ComponentPackage) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ComponentPackage) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ComponentPackage) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ComponentPackage) GetSpec() *ComponentPackageSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

// ComponentPackageSpec represents the spec for the component.
type ComponentPackageSpec struct {
	// Version-string for this component. The version should be a SemVer 2 string
	// (see https://semver.org/) of the form X.Y.Z (Major.Minor.Patch).  A
	// major-version changes should indicate breaking changes, minor-versions
	// should indicate backwards compatible features, and patch changes should
	// indicate backwards compatible. If there are any changes to the component,
	// then the version string must be incremented.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Optional. A version-string representing the version of the API this
	// component offers to other components (for the purposes of requirement
	// satisfaction). If no API is offered to other components, then this field
	// may be blank, but then other components may not depend on this component.
	ComponentApiVersion string `protobuf:"bytes,2,opt,name=componentApiVersion,proto3" json:"componentApiVersion,omitempty"`
	// A list of components that must be packaged in a bundle in with this
	// component.
	Requirements []*MinRequirement `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	// Structured Kubenetes objects that run as part of this app, whether on the
	// master, on the nodes, or in some other fashion.  These Kubernetes objects
	// are inlined and must be YAML/JSON compatible. Each must have `apiVersion`,
	// `kind`, and `metadata`.
	//
	// This is essentially equivalent to the Kubernetes `Unstructured` type.
	ClusterObjects []*_struct.Struct `protobuf:"bytes,4,rep,name=cluster_objects,json=clusterObjects,proto3" json:"cluster_objects,omitempty"`
	// Cluster objects that are specified via a File-URL. The process of inlining
	// a component turns cluster object files into cluster objects.
	// During the inline process, if the file is YAML-formatted and contains multiple
	// objects, the objects will be split into separate inline objects. In other
	// words, one cluster object file may result in multiple cluster objects.
	//
	// Each cluster object file must be parsable into a Struct: In other words,
	// it should be representable as either YAML or JSON.
	ClusterObjectFiles []*File `protobuf:"bytes,5,rep,name=cluster_object_files,json=clusterObjectFiles,proto3" json:"cluster_object_files,omitempty"`
	// Raw files represent arbitrary string data. Unlike cluster object files,
	// these files don't need to be parsable as YAML or JSON. So, during the
	// inline process, the data is inserted into a generated config map before
	// being added to the cluster objects. A ConfigMap is generated per-file,
	// with the metadata.name and the data-key both being set to the base-file
	// name. Thus, if the url is something like 'file://foo/bar/biff.txt', the
	// metadata.name and data-key will be 'biff.txt'.
	RawTextFiles         []*File  `protobuf:"bytes,6,rep,name=raw_text_files,json=rawTextFiles,proto3" json:"raw_text_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentPackageSpec) Reset()         { *m = ComponentPackageSpec{} }
func (m *ComponentPackageSpec) String() string { return proto.CompactTextString(m) }
func (*ComponentPackageSpec) ProtoMessage()    {}
func (*ComponentPackageSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_500109098fa4d83a, []int{1}
}

func (m *ComponentPackageSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentPackageSpec.Unmarshal(m, b)
}
func (m *ComponentPackageSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentPackageSpec.Marshal(b, m, deterministic)
}
func (m *ComponentPackageSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentPackageSpec.Merge(m, src)
}
func (m *ComponentPackageSpec) XXX_Size() int {
	return xxx_messageInfo_ComponentPackageSpec.Size(m)
}
func (m *ComponentPackageSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentPackageSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentPackageSpec proto.InternalMessageInfo

func (m *ComponentPackageSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ComponentPackageSpec) GetComponentApiVersion() string {
	if m != nil {
		return m.ComponentApiVersion
	}
	return ""
}

func (m *ComponentPackageSpec) GetRequirements() []*MinRequirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *ComponentPackageSpec) GetClusterObjects() []*_struct.Struct {
	if m != nil {
		return m.ClusterObjects
	}
	return nil
}

func (m *ComponentPackageSpec) GetClusterObjectFiles() []*File {
	if m != nil {
		return m.ClusterObjectFiles
	}
	return nil
}

func (m *ComponentPackageSpec) GetRawTextFiles() []*File {
	if m != nil {
		return m.RawTextFiles
	}
	return nil
}

// MinRequirement represents a component that this component must be packaged
// with in a ClusterBundle (or must be satisfied in some other fashion). This is
// roughly based on Semantic Import Versioning in the Go Language:
// https://research.swtch.com/vgo-import.
type MinRequirement struct {
	// Name of a component. The component name specified here must match exactly a
	// component name in the `metadata.name` field of another component.
	Component string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// The sem-ver apiVersion of the component. The API Version is only a minimum
	// requirement. The assumption any newer component with only backwards
	// compatible changes is acceptable.
	ComponentApiVersion  string   `protobuf:"bytes,2,opt,name=componentApiVersion,proto3" json:"componentApiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinRequirement) Reset()         { *m = MinRequirement{} }
func (m *MinRequirement) String() string { return proto.CompactTextString(m) }
func (*MinRequirement) ProtoMessage()    {}
func (*MinRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_500109098fa4d83a, []int{2}
}

func (m *MinRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinRequirement.Unmarshal(m, b)
}
func (m *MinRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinRequirement.Marshal(b, m, deterministic)
}
func (m *MinRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinRequirement.Merge(m, src)
}
func (m *MinRequirement) XXX_Size() int {
	return xxx_messageInfo_MinRequirement.Size(m)
}
func (m *MinRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_MinRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_MinRequirement proto.InternalMessageInfo

func (m *MinRequirement) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *MinRequirement) GetComponentApiVersion() string {
	if m != nil {
		return m.ComponentApiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*ComponentPackage)(nil), "pkg.apis.bundle.v1alpha1.ComponentPackage")
	proto.RegisterType((*ComponentPackageSpec)(nil), "pkg.apis.bundle.v1alpha1.ComponentPackageSpec")
	proto.RegisterType((*MinRequirement)(nil), "pkg.apis.bundle.v1alpha1.MinRequirement")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/component_package.proto", fileDescriptor_500109098fa4d83a)
}

var fileDescriptor_500109098fa4d83a = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x69, 0x19, 0xcc, 0x9b, 0x0a, 0x32, 0x93, 0xb0, 0xa6, 0x69, 0xaa, 0x2a, 0x1e, 0x2a,
	0xc4, 0x9c, 0x6d, 0xbc, 0xf0, 0x38, 0x36, 0x04, 0x12, 0xda, 0x44, 0x95, 0x21, 0x1e, 0x78, 0x09,
	0x8e, 0x73, 0x9b, 0x99, 0x24, 0xb6, 0xb1, 0x9d, 0x6d, 0xdf, 0xc0, 0xb7, 0xf1, 0x51, 0xa8, 0x76,
	0xd2, 0x12, 0xd4, 0x48, 0xf0, 0x16, 0xfb, 0x9e, 0x73, 0x72, 0xce, 0xbd, 0xd7, 0xe8, 0x58, 0x17,
	0x79, 0xc4, 0xb4, 0xb0, 0x51, 0x5a, 0xcb, 0xac, 0x84, 0xe8, 0xf6, 0x84, 0x95, 0xfa, 0x86, 0x9d,
	0x44, 0x5c, 0x55, 0x5a, 0x49, 0x90, 0x2e, 0xd1, 0x8c, 0x17, 0x2c, 0x07, 0xaa, 0x8d, 0x72, 0x0a,
	0x13, 0x5d, 0xe4, 0x74, 0xc9, 0xa0, 0x81, 0x41, 0x5b, 0xc6, 0xfe, 0x41, 0xae, 0x54, 0x5e, 0x42,
	0xe4, 0x71, 0x69, 0xbd, 0x88, 0xac, 0x33, 0x35, 0x77, 0x81, 0xb7, 0xff, 0xaa, 0xf7, 0x4f, 0xe1,
	0x9c, 0x70, 0x55, 0x55, 0x4a, 0x36, 0xe8, 0x97, 0xbd, 0x68, 0x95, 0x7e, 0x07, 0xee, 0x92, 0x0a,
	0x1c, 0x0b, 0xd8, 0xe9, 0xaf, 0x01, 0x7a, 0x7a, 0xd1, 0xba, 0x9d, 0x07, 0xb3, 0xf8, 0x10, 0x21,
	0xa6, 0xc5, 0x17, 0x30, 0x56, 0x28, 0x49, 0x06, 0x93, 0xc1, 0x6c, 0x3b, 0xfe, 0xe3, 0x06, 0x63,
	0x34, 0x2a, 0x84, 0xcc, 0xc8, 0x03, 0x5f, 0xf1, 0xdf, 0xf8, 0x0c, 0x3d, 0x5e, 0xca, 0x66, 0xcc,
	0x31, 0x32, 0x9c, 0x0c, 0x66, 0x3b, 0xa7, 0x2f, 0x68, 0x5f, 0x5a, 0xfa, 0xc9, 0xfb, 0xb8, 0x02,
	0xc7, 0xe2, 0x15, 0x0b, 0x9f, 0xa3, 0x91, 0xd5, 0xc0, 0xc9, 0xc8, 0xb3, 0x69, 0x3f, 0xfb, 0x6f,
	0xbf, 0xd7, 0x1a, 0x78, 0xec, 0xb9, 0xd3, 0x9f, 0x43, 0xb4, 0xb7, 0xa9, 0x8c, 0x09, 0x7a, 0x74,
	0xdb, 0xc9, 0xd3, 0x1e, 0xf1, 0x31, 0x7a, 0xb6, 0x1a, 0xd7, 0xdb, 0x75, 0xea, 0x90, 0x6d, 0x53,
	0x09, 0x5f, 0xa2, 0x5d, 0x03, 0x3f, 0x6a, 0x61, 0xa0, 0x02, 0xe9, 0x2c, 0x19, 0x4e, 0x86, 0xb3,
	0x9d, 0xd3, 0x59, 0xbf, 0xe1, 0x2b, 0x21, 0xe3, 0x35, 0x21, 0xee, 0xb0, 0xf1, 0x19, 0x7a, 0xc2,
	0xcb, 0xda, 0x3a, 0x30, 0x49, 0x18, 0x8f, 0x25, 0x23, 0x2f, 0xf8, 0x9c, 0x86, 0x9d, 0xa0, 0xed,
	0x4e, 0xd0, 0x6b, 0xbf, 0x13, 0xf1, 0xb8, 0xc1, 0x87, 0x2e, 0x5a, 0x3c, 0x47, 0x7b, 0x5d, 0x85,
	0x64, 0x21, 0x4a, 0xb0, 0xe4, 0xa1, 0x97, 0x39, 0xec, 0xf7, 0xf5, 0x5e, 0x94, 0x10, 0xe3, 0x8e,
	0xda, 0xf2, 0xca, 0xe2, 0x77, 0x68, 0x6c, 0xd8, 0x5d, 0xe2, 0xe0, 0xbe, 0xd5, 0xda, 0xfa, 0x27,
	0xad, 0x5d, 0xc3, 0xee, 0x3e, 0xc3, 0x7d, 0x50, 0x99, 0x7e, 0x43, 0xe3, 0x6e, 0x72, 0x7c, 0x80,
	0xb6, 0x57, 0x0d, 0x6d, 0xe6, 0xb0, 0xbe, 0xf8, 0xff, 0x49, 0x9c, 0x5f, 0x7e, 0xfd, 0x98, 0x0b,
	0x77, 0x53, 0xa7, 0x94, 0xab, 0x2a, 0xfa, 0xe0, 0xdb, 0x75, 0x51, 0xaa, 0x3a, 0x9b, 0x97, 0xcc,
	0x2d, 0x94, 0xa9, 0xa2, 0xe2, 0x8d, 0x3d, 0x6a, 0x02, 0x1e, 0x35, 0xaf, 0xa1, 0xef, 0x75, 0xa4,
	0x5b, 0xbe, 0xd1, 0xaf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xc9, 0x75, 0x88, 0xd8, 0x03,
	0x00, 0x00,
}
