// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/node_config.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Configuration for node images.
type NodeConfig struct {
	// Required. Kubernetes API Version for the NodeConfig type.
	// Should be 'gke.io/k8s-cluster-bundle/v1alpha1'
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Required. The Kubernetes `kind` for this object. Must always be
	// 'NodeConfig'.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kubernetes Metadata for the node config. The Metadata.name field must be
	// filled out and each node config in a bundle must have a unique name. For
	// example you might have a 'master-node-config' component or perhaps even a
	// 'gpu-config' config.
	Metadata *ObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Required. Version-string for this node config. The version should be a
	// SemVer 2 string (see https://semver.org/) of the form X.Y.Z
	// (Major.Minor.Patch). A major-version changes should indicate breaking
	// changes, minor-versions should indicate backwards compatible features, and
	// patch changes should indicate backwords compatible. If there are any
	// changes to the component, then the version string must be incremented.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Initialization file to run on VM startup. The contents of this init file
	// will depend a great deal on the specific environment and operation system.
	//
	// Types that are valid to be assigned to InitData:
	//	*NodeConfig_InitFile
	//	*NodeConfig_ExternalInitFile
	InitData isNodeConfig_InitData `protobuf_oneof:"init_data"`
	// Envirnoment variables to set before startup to configure the init script.
	EnvVars []*EnvVar `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	// The OS image to use for VM creation.
	OsImage              *File    `protobuf:"bytes,8,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec6b72b8a177a76, []int{0}
}
func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (m *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(m, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *NodeConfig) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *NodeConfig) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NodeConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type isNodeConfig_InitData interface {
	isNodeConfig_InitData()
}

type NodeConfig_InitFile struct {
	InitFile string `protobuf:"bytes,5,opt,name=init_file,json=initFile,proto3,oneof"`
}

type NodeConfig_ExternalInitFile struct {
	ExternalInitFile *File `protobuf:"bytes,6,opt,name=external_init_file,json=externalInitFile,proto3,oneof"`
}

func (*NodeConfig_InitFile) isNodeConfig_InitData() {}

func (*NodeConfig_ExternalInitFile) isNodeConfig_InitData() {}

func (m *NodeConfig) GetInitData() isNodeConfig_InitData {
	if m != nil {
		return m.InitData
	}
	return nil
}

func (m *NodeConfig) GetInitFile() string {
	if x, ok := m.GetInitData().(*NodeConfig_InitFile); ok {
		return x.InitFile
	}
	return ""
}

func (m *NodeConfig) GetExternalInitFile() *File {
	if x, ok := m.GetInitData().(*NodeConfig_ExternalInitFile); ok {
		return x.ExternalInitFile
	}
	return nil
}

func (m *NodeConfig) GetEnvVars() []*EnvVar {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *NodeConfig) GetOsImage() *File {
	if m != nil {
		return m.OsImage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NodeConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NodeConfig_OneofMarshaler, _NodeConfig_OneofUnmarshaler, _NodeConfig_OneofSizer, []interface{}{
		(*NodeConfig_InitFile)(nil),
		(*NodeConfig_ExternalInitFile)(nil),
	}
}

func _NodeConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExternalInitFile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NodeConfig.InitData has unexpected type %T", x)
	}
	return nil
}

func _NodeConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NodeConfig)
	switch tag {
	case 5: // init_data.init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.InitData = &NodeConfig_InitFile{x}
		return true, err
	case 6: // init_data.external_init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.InitData = &NodeConfig_ExternalInitFile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NodeConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.InitFile)))
		n += len(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		s := proto.Size(x.ExternalInitFile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// An environment variable specified for node startup.
type EnvVar struct {
	// Name of this environment variable. E.g., FOO_VAR. The name of the
	// environment variable should be unique within a node bootstrap
	// configuration.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value to set for this environment variable.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvVar) Reset()         { *m = EnvVar{} }
func (m *EnvVar) String() string { return proto.CompactTextString(m) }
func (*EnvVar) ProtoMessage()    {}
func (*EnvVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec6b72b8a177a76, []int{1}
}
func (m *EnvVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvVar.Unmarshal(m, b)
}
func (m *EnvVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvVar.Marshal(b, m, deterministic)
}
func (m *EnvVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvVar.Merge(m, src)
}
func (m *EnvVar) XXX_Size() int {
	return xxx_messageInfo_EnvVar.Size(m)
}
func (m *EnvVar) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvVar.DiscardUnknown(m)
}

var xxx_messageInfo_EnvVar proto.InternalMessageInfo

func (m *EnvVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeConfig)(nil), "pkg.apis.bundle.v1alpha1.NodeConfig")
	proto.RegisterType((*EnvVar)(nil), "pkg.apis.bundle.v1alpha1.EnvVar")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/node_config.proto", fileDescriptor_eec6b72b8a177a76)
}

var fileDescriptor_eec6b72b8a177a76 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0xd2, 0xdd, 0x26, 0xeb, 0x5e, 0x90, 0xc5, 0xc1, 0x5a, 0x89, 0x55, 0xb4, 0xe2, 0x50,
	0x21, 0x36, 0xd1, 0x96, 0x0b, 0x88, 0x0b, 0x6a, 0x05, 0xb4, 0x08, 0x0a, 0xca, 0xa1, 0x07, 0x2e,
	0x91, 0x93, 0x4c, 0x53, 0x13, 0xc7, 0x13, 0xc5, 0x4e, 0xc4, 0xcf, 0xe0, 0x27, 0x23, 0x3b, 0x09,
	0x70, 0x89, 0xb4, 0x27, 0x7b, 0x66, 0xde, 0xbc, 0x79, 0xf3, 0x41, 0x5e, 0xd6, 0x65, 0x11, 0xf1,
	0x5a, 0xe8, 0x28, 0x6d, 0x55, 0x2e, 0x21, 0xea, 0x1e, 0xb8, 0xac, 0xcf, 0xfc, 0x21, 0x52, 0x98,
	0x43, 0x92, 0xa1, 0x3a, 0x89, 0x22, 0xac, 0x1b, 0x34, 0x48, 0x59, 0x5d, 0x16, 0xa1, 0xc5, 0x86,
	0x3d, 0x36, 0x1c, 0xb1, 0x37, 0xaf, 0x26, 0x59, 0x7a, 0x3b, 0xc9, 0xb0, 0xaa, 0x50, 0xf5, 0x3c,
	0x37, 0xd3, 0x35, 0x31, 0xfd, 0x09, 0x99, 0x49, 0x2a, 0x30, 0xbc, 0xc7, 0xde, 0xfd, 0x9e, 0x13,
	0x72, 0xc0, 0x1c, 0xb6, 0x4e, 0x08, 0xbd, 0x25, 0x84, 0xd7, 0xe2, 0x08, 0x8d, 0x16, 0xa8, 0xd8,
	0x2c, 0x98, 0xad, 0xae, 0xe3, 0xff, 0x3c, 0x94, 0x92, 0xcb, 0x52, 0xa8, 0x9c, 0x3d, 0x71, 0x11,
	0xf7, 0xa7, 0xef, 0x89, 0x6f, 0x09, 0x73, 0x6e, 0x38, 0x9b, 0x07, 0xb3, 0xd5, 0x72, 0xfd, 0x22,
	0x9c, 0xea, 0x24, 0xfc, 0xe6, 0x14, 0x7c, 0x05, 0xc3, 0xe3, 0xbf, 0x59, 0x94, 0x11, 0xaf, 0x1b,
	0x4a, 0x5e, 0x3a, 0xe2, 0xd1, 0xa4, 0xcf, 0xc9, 0xb5, 0x50, 0xc2, 0x24, 0x27, 0x21, 0x81, 0x5d,
	0xd9, 0xd8, 0xee, 0x22, 0xf6, 0xad, 0xeb, 0xa3, 0x90, 0x40, 0x0f, 0x84, 0xc2, 0x2f, 0x03, 0x8d,
	0xe2, 0x32, 0xf9, 0x87, 0x5b, 0x38, 0x11, 0xb7, 0xd3, 0x22, 0x6c, 0xee, 0xee, 0x22, 0x7e, 0x3a,
	0xe6, 0xee, 0x47, 0xbe, 0x77, 0xc4, 0x07, 0xd5, 0x25, 0x1d, 0x6f, 0x34, 0xf3, 0x82, 0xf9, 0x6a,
	0xb9, 0x0e, 0xa6, 0x59, 0x3e, 0xa8, 0xee, 0xc8, 0x9b, 0xd8, 0x03, 0xf7, 0x6a, 0xfa, 0x96, 0xf8,
	0xa8, 0x13, 0x51, 0xf1, 0x02, 0x98, 0xff, 0x18, 0x09, 0xb1, 0x87, 0x7a, 0x6f, 0xe1, 0x9b, 0xe5,
	0xd0, 0xa6, 0x9d, 0xc6, 0xdd, 0x9a, 0x2c, 0x7a, 0x6a, 0x3b, 0x6d, 0xc5, 0x2b, 0x18, 0xf6, 0xe0,
	0xfe, 0xf4, 0x19, 0xb9, 0xea, 0xb8, 0x6c, 0x61, 0x58, 0x41, 0x6f, 0x6c, 0xbe, 0xfc, 0xf8, 0x5c,
	0x08, 0x73, 0x6e, 0xd3, 0x30, 0xc3, 0x2a, 0xfa, 0x84, 0x58, 0x48, 0xd8, 0x4a, 0x6c, 0xf3, 0xef,
	0x92, 0x9b, 0x13, 0x36, 0x55, 0x54, 0xbe, 0xd1, 0xf7, 0x99, 0x6c, 0xb5, 0x81, 0xe6, 0x7e, 0x38,
	0x8b, 0xa9, 0x33, 0x49, 0x17, 0xee, 0x36, 0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xde, 0x0c,
	0x2b, 0xbe, 0xbd, 0x02, 0x00, 0x00,
}
