// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/node_config.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Configuration for node images.
type NodeConfig struct {
	// The name of this image configuration.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version for this node configuration.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Initialization file to run on VM startup. The contents of this init file
	// will depend a great deal on the specific environment and operation system.
	//
	// Types that are valid to be assigned to InitData:
	//	*NodeConfig_InitFile
	//	*NodeConfig_ExternalInitFile
	InitData isNodeConfig_InitData `protobuf_oneof:"init_data"`
	// Envirnoment variables to set before startup to configure the init script.
	EnvVars []*EnvVar `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	// The OS image to use for VM creation.
	OsImage              *File    `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec6b72b8a177a76, []int{0}
}

func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (m *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(m, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type isNodeConfig_InitData interface {
	isNodeConfig_InitData()
}

type NodeConfig_InitFile struct {
	InitFile string `protobuf:"bytes,3,opt,name=init_file,json=initFile,proto3,oneof"`
}

type NodeConfig_ExternalInitFile struct {
	ExternalInitFile *File `protobuf:"bytes,4,opt,name=external_init_file,json=externalInitFile,proto3,oneof"`
}

func (*NodeConfig_InitFile) isNodeConfig_InitData() {}

func (*NodeConfig_ExternalInitFile) isNodeConfig_InitData() {}

func (m *NodeConfig) GetInitData() isNodeConfig_InitData {
	if m != nil {
		return m.InitData
	}
	return nil
}

func (m *NodeConfig) GetInitFile() string {
	if x, ok := m.GetInitData().(*NodeConfig_InitFile); ok {
		return x.InitFile
	}
	return ""
}

func (m *NodeConfig) GetExternalInitFile() *File {
	if x, ok := m.GetInitData().(*NodeConfig_ExternalInitFile); ok {
		return x.ExternalInitFile
	}
	return nil
}

func (m *NodeConfig) GetEnvVars() []*EnvVar {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *NodeConfig) GetOsImage() *File {
	if m != nil {
		return m.OsImage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NodeConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NodeConfig_OneofMarshaler, _NodeConfig_OneofUnmarshaler, _NodeConfig_OneofSizer, []interface{}{
		(*NodeConfig_InitFile)(nil),
		(*NodeConfig_ExternalInitFile)(nil),
	}
}

func _NodeConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExternalInitFile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NodeConfig.InitData has unexpected type %T", x)
	}
	return nil
}

func _NodeConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NodeConfig)
	switch tag {
	case 3: // init_data.init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.InitData = &NodeConfig_InitFile{x}
		return true, err
	case 4: // init_data.external_init_file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.InitData = &NodeConfig_ExternalInitFile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NodeConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NodeConfig)
	// init_data
	switch x := m.InitData.(type) {
	case *NodeConfig_InitFile:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.InitFile)))
		n += len(x.InitFile)
	case *NodeConfig_ExternalInitFile:
		s := proto.Size(x.ExternalInitFile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// An environment variable specified for node startup.
type EnvVar struct {
	// Name of this environment variable. E.g., FOO_VAR. The name of the
	// environment variable should be unique within a node bootstrap
	// configuration.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value to set for this environment variable.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvVar) Reset()         { *m = EnvVar{} }
func (m *EnvVar) String() string { return proto.CompactTextString(m) }
func (*EnvVar) ProtoMessage()    {}
func (*EnvVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec6b72b8a177a76, []int{1}
}

func (m *EnvVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvVar.Unmarshal(m, b)
}
func (m *EnvVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvVar.Marshal(b, m, deterministic)
}
func (m *EnvVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvVar.Merge(m, src)
}
func (m *EnvVar) XXX_Size() int {
	return xxx_messageInfo_EnvVar.Size(m)
}
func (m *EnvVar) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvVar.DiscardUnknown(m)
}

var xxx_messageInfo_EnvVar proto.InternalMessageInfo

func (m *EnvVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeConfig)(nil), "pkg.apis.bundle.v1alpha1.NodeConfig")
	proto.RegisterType((*EnvVar)(nil), "pkg.apis.bundle.v1alpha1.EnvVar")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/node_config.proto", fileDescriptor_eec6b72b8a177a76)
}

var fileDescriptor_eec6b72b8a177a76 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x3d, 0x6b, 0xfb, 0x30,
	0x10, 0xc6, 0xf3, 0xfe, 0xa2, 0x2c, 0x7f, 0xc4, 0x7f, 0x30, 0x85, 0x16, 0x93, 0x29, 0x94, 0x46,
	0x26, 0xe9, 0xd2, 0xd2, 0x2d, 0xa1, 0x6d, 0x52, 0x4a, 0x28, 0x1e, 0x3a, 0x74, 0x31, 0x8a, 0x7d,
	0x71, 0x44, 0x64, 0x9d, 0x91, 0x64, 0xd3, 0x4f, 0xd5, 0xcf, 0x58, 0x6c, 0xc7, 0x74, 0xa9, 0xa1,
	0x93, 0xf4, 0x9c, 0x9e, 0xfb, 0xa1, 0xbb, 0x87, 0x5c, 0xa7, 0xa7, 0xd8, 0xe3, 0xa9, 0x30, 0xde,
	0x3e, 0x53, 0x91, 0x04, 0x2f, 0x5f, 0x70, 0x99, 0x1e, 0xf9, 0xc2, 0x53, 0x18, 0x41, 0x10, 0xa2,
	0x3a, 0x88, 0x98, 0xa5, 0x1a, 0x2d, 0x52, 0x27, 0x3d, 0xc5, 0xac, 0xf0, 0xb2, 0xca, 0xcb, 0x6a,
	0xef, 0xc5, 0x4d, 0x23, 0xa5, 0xd2, 0x41, 0x88, 0x49, 0x82, 0xaa, 0xe2, 0x4c, 0xbf, 0x3a, 0x84,
	0xec, 0x30, 0x82, 0x75, 0x09, 0xa7, 0x94, 0xf4, 0x14, 0x4f, 0xc0, 0x69, 0xbb, 0xed, 0xd9, 0xd8,
	0x2f, 0xef, 0xd4, 0x21, 0xc3, 0x1c, 0xb4, 0x11, 0xa8, 0x9c, 0x4e, 0x59, 0xae, 0x25, 0xbd, 0x24,
	0x63, 0xa1, 0x84, 0x0d, 0x0e, 0x42, 0x82, 0xd3, 0x2d, 0xde, 0x36, 0x2d, 0x7f, 0x54, 0x94, 0x9e,
	0x84, 0x04, 0xba, 0x23, 0x14, 0x3e, 0x2d, 0x68, 0xc5, 0x65, 0xf0, 0xe3, 0xeb, 0xb9, 0xed, 0xd9,
	0x64, 0x79, 0xc5, 0x9a, 0x06, 0x60, 0x45, 0xef, 0xa6, 0xe5, 0xff, 0xab, 0x7b, 0xb7, 0x35, 0xef,
	0x81, 0x8c, 0x40, 0xe5, 0x41, 0xce, 0xb5, 0x71, 0xfa, 0x6e, 0x77, 0x36, 0x59, 0xba, 0xcd, 0x94,
	0x47, 0x95, 0xbf, 0x73, 0xed, 0x0f, 0xa1, 0x3c, 0x0d, 0xbd, 0x27, 0x23, 0x34, 0x81, 0x48, 0x78,
	0x0c, 0xce, 0xe0, 0x2f, 0x5f, 0xf0, 0x87, 0x68, 0xb6, 0x85, 0x7d, 0x35, 0x39, 0x8f, 0x19, 0x71,
	0xcb, 0xa7, 0x4b, 0x32, 0xa8, 0xd0, 0xbf, 0xee, 0xea, 0x3f, 0xe9, 0xe7, 0x5c, 0x66, 0x70, 0xde,
	0x54, 0x25, 0x56, 0xaf, 0x1f, 0x2f, 0xb1, 0xb0, 0xc7, 0x6c, 0xcf, 0x42, 0x4c, 0xbc, 0x67, 0xc4,
	0x58, 0xc2, 0x5a, 0x62, 0x16, 0xbd, 0x49, 0x6e, 0x0f, 0xa8, 0x13, 0xef, 0x74, 0x67, 0xe6, 0xa1,
	0xcc, 0x8c, 0x05, 0x3d, 0x3f, 0xc7, 0xd6, 0x14, 0xe3, 0x7e, 0x50, 0x26, 0x77, 0xfb, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xb0, 0x85, 0x3c, 0x0e, 0x2f, 0x02, 0x00, 0x00,
}
