// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/overlay.proto

package v1alpha1 // import "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Whether the overlay is required or optional.
type OverlayConstraint int32

const (
	// Default proto case. Equivalent to required.
	OverlayConstraint_UNKNOWN_PATCH_USAGE OverlayConstraint = 0
	// This overlay must always be applied. If the relevant parameters are not
	// specified, it is an error.
	OverlayConstraint_REQUIRED OverlayConstraint = 1
	// Overlays with this type are optional and only applied of all the parameters
	// are supplied.
	OverlayConstraint_OPTIONAL OverlayConstraint = 2
)

var OverlayConstraint_name = map[int32]string{
	0: "UNKNOWN_PATCH_USAGE",
	1: "REQUIRED",
	2: "OPTIONAL",
}

var OverlayConstraint_value = map[string]int32{
	"UNKNOWN_PATCH_USAGE": 0,
	"REQUIRED":            1,
	"OPTIONAL":            2,
}

func (x OverlayConstraint) String() string {
	return proto.EnumName(OverlayConstraint_name, int32(x))
}

func (OverlayConstraint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41687f867ae1923e, []int{0}
}

// A collection of Overlays that apply to a specific object.
type OverlayCollection struct {
	Overlays             []*Overlay `protobuf:"bytes,1,rep,name=overlays,proto3" json:"overlays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OverlayCollection) Reset()         { *m = OverlayCollection{} }
func (m *OverlayCollection) String() string { return proto.CompactTextString(m) }
func (*OverlayCollection) ProtoMessage()    {}
func (*OverlayCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_41687f867ae1923e, []int{0}
}
func (m *OverlayCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OverlayCollection.Unmarshal(m, b)
}
func (m *OverlayCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OverlayCollection.Marshal(b, m, deterministic)
}
func (m *OverlayCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OverlayCollection.Merge(m, src)
}
func (m *OverlayCollection) XXX_Size() int {
	return xxx_messageInfo_OverlayCollection.Size(m)
}
func (m *OverlayCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_OverlayCollection.DiscardUnknown(m)
}

var xxx_messageInfo_OverlayCollection proto.InternalMessageInfo

func (m *OverlayCollection) GetOverlays() []*Overlay {
	if m != nil {
		return m.Overlays
	}
	return nil
}

// Overlay provides functionality for patching Kubernetes objects. This
// relies on the strategic merge patch functionality from kubernetes.
type Overlay struct {
	// Required. Name provides an identifier for this overlay.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Kubernetes GVK for a custom resource that provides the options
	// (parameters) for this Overlay.
	CustomResourceKey *GroupVersionKind `protobuf:"bytes,2,opt,name=custom_resource_key,json=customResourceKey,proto3" json:"custom_resource_key,omitempty"`
	// Required. The patch itself. A templated YAML that's meant to be applied via
	// strategic-merge-patch.  The patch itself must be specified as a
	// Go-Templatized YAML.
	TemplateString string `protobuf:"bytes,3,opt,name=template_string,json=templateString,proto3" json:"template_string,omitempty"`
	// The usage constraint for this overlay.
	OverlayConstraint    OverlayConstraint `protobuf:"varint,4,opt,name=overlay_constraint,json=overlayConstraint,proto3,enum=pkg.apis.bundle.v1alpha1.OverlayConstraint" json:"overlay_constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Overlay) Reset()         { *m = Overlay{} }
func (m *Overlay) String() string { return proto.CompactTextString(m) }
func (*Overlay) ProtoMessage()    {}
func (*Overlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_41687f867ae1923e, []int{1}
}
func (m *Overlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Overlay.Unmarshal(m, b)
}
func (m *Overlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Overlay.Marshal(b, m, deterministic)
}
func (m *Overlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Overlay.Merge(m, src)
}
func (m *Overlay) XXX_Size() int {
	return xxx_messageInfo_Overlay.Size(m)
}
func (m *Overlay) XXX_DiscardUnknown() {
	xxx_messageInfo_Overlay.DiscardUnknown(m)
}

var xxx_messageInfo_Overlay proto.InternalMessageInfo

func (m *Overlay) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Overlay) GetCustomResourceKey() *GroupVersionKind {
	if m != nil {
		return m.CustomResourceKey
	}
	return nil
}

func (m *Overlay) GetTemplateString() string {
	if m != nil {
		return m.TemplateString
	}
	return ""
}

func (m *Overlay) GetOverlayConstraint() OverlayConstraint {
	if m != nil {
		return m.OverlayConstraint
	}
	return OverlayConstraint_UNKNOWN_PATCH_USAGE
}

func init() {
	proto.RegisterType((*OverlayCollection)(nil), "pkg.apis.bundle.v1alpha1.OverlayCollection")
	proto.RegisterType((*Overlay)(nil), "pkg.apis.bundle.v1alpha1.Overlay")
	proto.RegisterEnum("pkg.apis.bundle.v1alpha1.OverlayConstraint", OverlayConstraint_name, OverlayConstraint_value)
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/overlay.proto", fileDescriptor_41687f867ae1923e)
}

var fileDescriptor_41687f867ae1923e = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x8f, 0xd2, 0x40,
	0x18, 0xc5, 0xed, 0xee, 0x46, 0xd7, 0x59, 0xb3, 0xc2, 0x70, 0xb0, 0xf1, 0x54, 0x39, 0x68, 0x83,
	0xd2, 0x06, 0xbc, 0x78, 0xf1, 0x80, 0x95, 0x00, 0x42, 0x5a, 0x1c, 0x40, 0x13, 0x2e, 0xcd, 0x50,
	0xc6, 0xd2, 0x74, 0x3a, 0x5f, 0x33, 0x33, 0x25, 0xe1, 0x9f, 0x37, 0x86, 0xb6, 0x10, 0x63, 0xd2,
	0x78, 0xeb, 0xf7, 0xf2, 0xde, 0xef, 0x75, 0xe6, 0x1b, 0xf4, 0x36, 0x4f, 0x63, 0x97, 0xe6, 0x89,
	0x72, 0x77, 0x85, 0xd8, 0x73, 0xe6, 0x1e, 0x07, 0x94, 0xe7, 0x07, 0x3a, 0x70, 0xe1, 0xc8, 0x24,
	0xa7, 0x27, 0x27, 0x97, 0xa0, 0x01, 0x9b, 0x79, 0x1a, 0x3b, 0x67, 0x9f, 0x53, 0xf9, 0x9c, 0x8b,
	0xef, 0xf5, 0x87, 0x46, 0x42, 0x35, 0x87, 0x11, 0x64, 0x19, 0x88, 0x8a, 0xd3, 0x25, 0xa8, 0x1d,
	0x54, 0x60, 0x0f, 0x38, 0x67, 0x91, 0x4e, 0x40, 0xe0, 0xcf, 0xe8, 0xbe, 0x6e, 0x53, 0xa6, 0x61,
	0xdd, 0xda, 0x0f, 0xc3, 0x37, 0x4e, 0x53, 0x9f, 0x53, 0xc7, 0xc9, 0x35, 0xd2, 0xfd, 0x6d, 0xa0,
	0x67, 0xb5, 0x8a, 0x31, 0xba, 0x13, 0x34, 0x63, 0xa6, 0x61, 0x19, 0xf6, 0x73, 0x52, 0x7e, 0xe3,
	0x2d, 0xea, 0x44, 0x85, 0xd2, 0x90, 0x85, 0x92, 0x29, 0x28, 0x64, 0xc4, 0xc2, 0x94, 0x9d, 0xcc,
	0x1b, 0xcb, 0xb0, 0x1f, 0x86, 0xbd, 0xe6, 0xa6, 0x89, 0x84, 0x22, 0xff, 0xc1, 0xa4, 0x4a, 0x40,
	0xcc, 0x13, 0xb1, 0x27, 0xed, 0x0a, 0x43, 0x6a, 0xca, 0x9c, 0x9d, 0xf0, 0x3b, 0xf4, 0x52, 0xb3,
	0x2c, 0xe7, 0x54, 0xb3, 0x50, 0x69, 0x99, 0x88, 0xd8, 0xbc, 0x2d, 0xab, 0x1f, 0x2f, 0xf2, 0xaa,
	0x54, 0xf1, 0x16, 0xe1, 0xfa, 0x87, 0xc3, 0x08, 0x84, 0xd2, 0x92, 0x26, 0x42, 0x9b, 0x77, 0x96,
	0x61, 0x3f, 0x0e, 0xdf, 0xff, 0xf7, 0xb4, 0xde, 0x35, 0x42, 0xda, 0xf0, 0xaf, 0xd4, 0x9b, 0xfe,
	0x75, 0xa9, 0x17, 0x11, 0xbf, 0x42, 0x9d, 0x8d, 0x3f, 0xf7, 0x83, 0x9f, 0x7e, 0xb8, 0x1c, 0xad,
	0xbd, 0x69, 0xb8, 0x59, 0x8d, 0x26, 0xe3, 0xd6, 0x13, 0xfc, 0x02, 0xdd, 0x93, 0xf1, 0xf7, 0xcd,
	0x8c, 0x8c, 0xbf, 0xb6, 0x8c, 0xf3, 0x14, 0x2c, 0xd7, 0xb3, 0xc0, 0x1f, 0x2d, 0x5a, 0x37, 0x5f,
	0x16, 0xdb, 0x6f, 0x71, 0xa2, 0x0f, 0xc5, 0xce, 0x89, 0x20, 0x73, 0x27, 0x00, 0x31, 0x67, 0x1e,
	0x87, 0x62, 0xbf, 0xe4, 0x54, 0xff, 0x02, 0x99, 0xb9, 0xe9, 0x27, 0xd5, 0x8f, 0x78, 0xa1, 0x34,
	0x93, 0xfd, 0x7a, 0xe1, 0x4d, 0x0f, 0x60, 0xf7, 0xb4, 0xdc, 0xf9, 0xc7, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x01, 0x71, 0x20, 0x4b, 0x65, 0x02, 0x00, 0x00,
}
