// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/bundle/v1alpha1/patch.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A collection of Patches that apply to a specific object.
type PatchCollection struct {
	Patches              []*Patch `protobuf:"bytes,1,rep,name=patches,proto3" json:"patches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchCollection) Reset()         { *m = PatchCollection{} }
func (m *PatchCollection) String() string { return proto.CompactTextString(m) }
func (*PatchCollection) ProtoMessage()    {}
func (*PatchCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1dd2794b59d847d, []int{0}
}

func (m *PatchCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCollection.Unmarshal(m, b)
}
func (m *PatchCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCollection.Marshal(b, m, deterministic)
}
func (m *PatchCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCollection.Merge(m, src)
}
func (m *PatchCollection) XXX_Size() int {
	return xxx_messageInfo_PatchCollection.Size(m)
}
func (m *PatchCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCollection.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCollection proto.InternalMessageInfo

func (m *PatchCollection) GetPatches() []*Patch {
	if m != nil {
		return m.Patches
	}
	return nil
}

// Patch provides functionality for patching Kubernetes objects. This
// relies on the strategic merge patch functionality from kubernetes.
type Patch struct {
	// Required. Name provides an identifier for this patch.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Kubernetes object reference for a custom resource that provides the
	// options (parameters) for this Patch.
	ObjectRef *ObjectReference `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	// Required. The patch itself. A templated YAML that's meant to be applied via
	// strategic-merge-patch.  The patch itself must be specified as a
	// Go-Templatized YAML.
	TemplateString string `protobuf:"bytes,3,opt,name=template_string,json=templateString,proto3" json:"template_string,omitempty"`
	// Whether this patch is required (or optional) to be applied.
	IsRequired           bool     `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patch) Reset()         { *m = Patch{} }
func (m *Patch) String() string { return proto.CompactTextString(m) }
func (*Patch) ProtoMessage()    {}
func (*Patch) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1dd2794b59d847d, []int{1}
}

func (m *Patch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch.Unmarshal(m, b)
}
func (m *Patch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch.Marshal(b, m, deterministic)
}
func (m *Patch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch.Merge(m, src)
}
func (m *Patch) XXX_Size() int {
	return xxx_messageInfo_Patch.Size(m)
}
func (m *Patch) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch.DiscardUnknown(m)
}

var xxx_messageInfo_Patch proto.InternalMessageInfo

func (m *Patch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Patch) GetObjectRef() *ObjectReference {
	if m != nil {
		return m.ObjectRef
	}
	return nil
}

func (m *Patch) GetTemplateString() string {
	if m != nil {
		return m.TemplateString
	}
	return ""
}

func (m *Patch) GetIsRequired() bool {
	if m != nil {
		return m.IsRequired
	}
	return false
}

func init() {
	proto.RegisterType((*PatchCollection)(nil), "pkg.apis.bundle.v1alpha1.PatchCollection")
	proto.RegisterType((*Patch)(nil), "pkg.apis.bundle.v1alpha1.Patch")
}

func init() {
	proto.RegisterFile("pkg/apis/bundle/v1alpha1/patch.proto", fileDescriptor_a1dd2794b59d847d)
}

var fileDescriptor_a1dd2794b59d847d = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xa9, 0x9b, 0x7f, 0x96, 0x81, 0x83, 0x9c, 0x8a, 0x97, 0x95, 0x21, 0x58, 0xc1, 0xa5,
	0x6c, 0x5e, 0xf4, 0xea, 0x0e, 0x8a, 0x0c, 0x1c, 0xf5, 0xe6, 0xa5, 0xa4, 0xd9, 0xbb, 0x2e, 0x2e,
	0xcd, 0x1b, 0x93, 0xd4, 0xaf, 0xe5, 0x57, 0x94, 0xa5, 0xeb, 0xb1, 0xb7, 0xe4, 0xc7, 0xef, 0x7d,
	0x1e, 0x78, 0xc8, 0xad, 0x39, 0x54, 0x19, 0x37, 0xd2, 0x65, 0x65, 0xa3, 0xb7, 0x0a, 0xb2, 0xdf,
	0x05, 0x57, 0x66, 0xcf, 0x17, 0x99, 0xe1, 0x5e, 0xec, 0x99, 0xb1, 0xe8, 0x91, 0xc6, 0xe6, 0x50,
	0xb1, 0xa3, 0xc5, 0x5a, 0x8b, 0x75, 0xd6, 0xcd, 0x43, 0xef, 0x7d, 0xfb, 0x2f, 0x04, 0xd6, 0x35,
	0xea, 0x36, 0x67, 0xb6, 0x26, 0x93, 0xcd, 0x31, 0x76, 0x85, 0x4a, 0x81, 0xf0, 0x12, 0x35, 0x7d,
	0x26, 0x97, 0xa1, 0x09, 0x5c, 0x1c, 0x25, 0x83, 0x74, 0xbc, 0x9c, 0xb2, 0xbe, 0x32, 0x16, 0x6e,
	0xf3, 0xce, 0x9f, 0xfd, 0x45, 0xe4, 0x3c, 0x20, 0x4a, 0xc9, 0x50, 0xf3, 0x1a, 0xe2, 0x28, 0x89,
	0xd2, 0x51, 0x1e, 0xde, 0xf4, 0x8d, 0x10, 0x2c, 0xbf, 0x41, 0xf8, 0xc2, 0xc2, 0x2e, 0x3e, 0x4b,
	0xa2, 0x74, 0xbc, 0xbc, 0xef, 0xcf, 0xfe, 0x08, 0x6e, 0x0e, 0x3b, 0xb0, 0xa0, 0x05, 0xe4, 0x23,
	0xec, 0x00, 0xbd, 0x23, 0x13, 0x0f, 0xb5, 0x51, 0xdc, 0x43, 0xe1, 0xbc, 0x95, 0xba, 0x8a, 0x07,
	0xa1, 0xe8, 0xba, 0xc3, 0x9f, 0x81, 0xd2, 0x29, 0x19, 0x4b, 0x57, 0x58, 0xf8, 0x69, 0xa4, 0x85,
	0x6d, 0x3c, 0x4c, 0xa2, 0xf4, 0x2a, 0x27, 0xd2, 0xe5, 0x27, 0xf2, 0xb2, 0xfe, 0x7a, 0xaf, 0xa4,
	0xdf, 0x37, 0x25, 0x13, 0x58, 0x67, 0xaf, 0x88, 0x95, 0x82, 0x95, 0xc2, 0x66, 0xbb, 0x51, 0xdc,
	0xef, 0xd0, 0xd6, 0xd9, 0xe1, 0xc9, 0xcd, 0x85, 0x6a, 0x9c, 0x07, 0x3b, 0x3f, 0x2d, 0xda, 0xb7,
	0x70, 0x79, 0x11, 0x46, 0x7d, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x46, 0xc1, 0x4e, 0xc4,
	0x01, 0x00, 0x00,
}
