// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"
	scheme "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PackageDeploymentsGetter has a method to return a PackageDeploymentInterface.
// A group's client should implement this interface.
type PackageDeploymentsGetter interface {
	PackageDeployments(namespace string) PackageDeploymentInterface
}

// PackageDeploymentInterface has methods to work with PackageDeployment resources.
type PackageDeploymentInterface interface {
	Create(*v1alpha1.PackageDeployment) (*v1alpha1.PackageDeployment, error)
	Update(*v1alpha1.PackageDeployment) (*v1alpha1.PackageDeployment, error)
	UpdateStatus(*v1alpha1.PackageDeployment) (*v1alpha1.PackageDeployment, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PackageDeployment, error)
	List(opts v1.ListOptions) (*v1alpha1.PackageDeploymentList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PackageDeployment, err error)
	PackageDeploymentExpansion
}

// packageDeployments implements PackageDeploymentInterface
type packageDeployments struct {
	client rest.Interface
	ns     string
}

// newPackageDeployments returns a PackageDeployments
func newPackageDeployments(c *BundleV1alpha1Client, namespace string) *packageDeployments {
	return &packageDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the packageDeployment, and returns the corresponding packageDeployment object, and an error if there is any.
func (c *packageDeployments) Get(name string, options v1.GetOptions) (result *v1alpha1.PackageDeployment, err error) {
	result = &v1alpha1.PackageDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagedeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PackageDeployments that match those selectors.
func (c *packageDeployments) List(opts v1.ListOptions) (result *v1alpha1.PackageDeploymentList, err error) {
	result = &v1alpha1.PackageDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagedeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested packageDeployments.
func (c *packageDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("packagedeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a packageDeployment and creates it.  Returns the server's representation of the packageDeployment, and an error, if there is any.
func (c *packageDeployments) Create(packageDeployment *v1alpha1.PackageDeployment) (result *v1alpha1.PackageDeployment, err error) {
	result = &v1alpha1.PackageDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("packagedeployments").
		Body(packageDeployment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a packageDeployment and updates it. Returns the server's representation of the packageDeployment, and an error, if there is any.
func (c *packageDeployments) Update(packageDeployment *v1alpha1.PackageDeployment) (result *v1alpha1.PackageDeployment, err error) {
	result = &v1alpha1.PackageDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packagedeployments").
		Name(packageDeployment.Name).
		Body(packageDeployment).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *packageDeployments) UpdateStatus(packageDeployment *v1alpha1.PackageDeployment) (result *v1alpha1.PackageDeployment, err error) {
	result = &v1alpha1.PackageDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packagedeployments").
		Name(packageDeployment.Name).
		SubResource("status").
		Body(packageDeployment).
		Do().
		Into(result)
	return
}

// Delete takes name of the packageDeployment and deletes it. Returns an error if one occurs.
func (c *packageDeployments) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagedeployments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *packageDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagedeployments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched packageDeployment.
func (c *packageDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PackageDeployment, err error) {
	result = &v1alpha1.PackageDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("packagedeployments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
