// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/apis/bundle/v1alpha1"
	scheme "github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PackageDeploymentClassesGetter has a method to return a PackageDeploymentClassInterface.
// A group's client should implement this interface.
type PackageDeploymentClassesGetter interface {
	PackageDeploymentClasses(namespace string) PackageDeploymentClassInterface
}

// PackageDeploymentClassInterface has methods to work with PackageDeploymentClass resources.
type PackageDeploymentClassInterface interface {
	Create(*v1alpha1.PackageDeploymentClass) (*v1alpha1.PackageDeploymentClass, error)
	Update(*v1alpha1.PackageDeploymentClass) (*v1alpha1.PackageDeploymentClass, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PackageDeploymentClass, error)
	List(opts v1.ListOptions) (*v1alpha1.PackageDeploymentClassList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PackageDeploymentClass, err error)
	PackageDeploymentClassExpansion
}

// packageDeploymentClasses implements PackageDeploymentClassInterface
type packageDeploymentClasses struct {
	client rest.Interface
	ns     string
}

// newPackageDeploymentClasses returns a PackageDeploymentClasses
func newPackageDeploymentClasses(c *BundleV1alpha1Client, namespace string) *packageDeploymentClasses {
	return &packageDeploymentClasses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the packageDeploymentClass, and returns the corresponding packageDeploymentClass object, and an error if there is any.
func (c *packageDeploymentClasses) Get(name string, options v1.GetOptions) (result *v1alpha1.PackageDeploymentClass, err error) {
	result = &v1alpha1.PackageDeploymentClass{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PackageDeploymentClasses that match those selectors.
func (c *packageDeploymentClasses) List(opts v1.ListOptions) (result *v1alpha1.PackageDeploymentClassList, err error) {
	result = &v1alpha1.PackageDeploymentClassList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested packageDeploymentClasses.
func (c *packageDeploymentClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a packageDeploymentClass and creates it.  Returns the server's representation of the packageDeploymentClass, and an error, if there is any.
func (c *packageDeploymentClasses) Create(packageDeploymentClass *v1alpha1.PackageDeploymentClass) (result *v1alpha1.PackageDeploymentClass, err error) {
	result = &v1alpha1.PackageDeploymentClass{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		Body(packageDeploymentClass).
		Do().
		Into(result)
	return
}

// Update takes the representation of a packageDeploymentClass and updates it. Returns the server's representation of the packageDeploymentClass, and an error, if there is any.
func (c *packageDeploymentClasses) Update(packageDeploymentClass *v1alpha1.PackageDeploymentClass) (result *v1alpha1.PackageDeploymentClass, err error) {
	result = &v1alpha1.PackageDeploymentClass{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		Name(packageDeploymentClass.Name).
		Body(packageDeploymentClass).
		Do().
		Into(result)
	return
}

// Delete takes name of the packageDeploymentClass and deletes it. Returns an error if one occurs.
func (c *packageDeploymentClasses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *packageDeploymentClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched packageDeploymentClass.
func (c *packageDeploymentClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PackageDeploymentClass, err error) {
	result = &v1alpha1.PackageDeploymentClass{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("packagedeploymentclasses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
