apiVersion: bundle.gke.io/v1alpha1
kind: PatchTemplateBuilder
buildSchema:
  required:
    - ImageTag
  properties:
    ImageTag:
      description: The image tag to deploy.
      type: string
    PortStartGuard:
      description: Start stanza for the port
      type: string
      default: "{{if ge .Port 1.0}}"
    PortEndGuard:
      description: End stanza for the port
      type: string
      default: "{{end}}"
targetSchema:
  required:
    - Namespace
  properties:
    Namespace:
      description: The namespace in which to deploy the app.
      type: string
    Registry:
      description: The registry from which the image should be pulled.
      type: string
      default: gcr.io/google-samples
    Port:
      description: Container port for the helloweb app.
      type: number
      default: 8080
template: |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: {{.Namespace}}
    name: helloweb
  spec:
    template:
      spec:
        containers:
        - name: hello-app
          image: {{ .Registry }}/hello-app:{{ .ImageTag }}
          {{ .PortStartGuard }}
          ports:
          - containerPort: {{ .Port }}
          {{ .PortEndGuard }}
