apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  selector:
    matchLabels:
      component: kube-scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      name: kube-scheduler
      labels:
        component: kube-scheduler
        tier: control-plane
    spec:
      containers:
        - name: kube-scheduler
          image: k8s.gcr.io/kube-scheduler-amd64:1.11.7
          command:
            - kube-scheduler
            - --address=0.0.0.0
            - --port=10251
            - --kubeconfig=/etc/kubernetes/scheduler.conf
            - --leader-elect=true
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: etc-ssl-certs
              readOnly: true
              mountPath: /etc/ssl/certs
            - name: kube-scheduler
              readOnly: true
              mountPath: /etc/kubernetes
      volumes:
        - name: etc-ssl-certs
          hostPath:
            path: /etc/ssl/certs
            type: DirectoryOrCreate
        - name: kube-scheduler
          secret:
            secretName: kube-scheduler
